MLIR: lib/TableGen/Class.cpp File Reference
Class.cpp File Reference
#include "mlir/TableGen/Class.h"
#include "mlir/TableGen/Format.h"
#include "llvm/ADT/Sequence.h"
#include "llvm/ADT/Twine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include <unordered_set>
Macros
#define DEBUG_TYPE "mlir-tblgen-opclass"
Functions
static StringRef getSpaceAfterType (StringRef type)
template<typename ContainerT , typename MethodT >
MethodT * insertAndPrune (ContainerT &methods, MethodT newMethod)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "mlir-tblgen-opclass"
Definition at line 18 of file Class.cpp.
Function Documentation
getSpaceAfterType()
static StringRef getSpaceAfterType (StringRef type) static
Definition at line 25 of file Class.cpp.
References mlir::tblgen::MethodParameter::hasDefaultValue().
Referenced by mlir::tblgen::MethodSignature::writeDeclTo(), and mlir::tblgen::MethodSignature::writeDefTo().
insertAndPrune()
template<typename ContainerT , typename MethodT > MethodT* insertAndPrune (ContainerT & methods, MethodT newMethod)
Definition at line 233 of file Class.cpp.
Referenced by mlir::tblgen::Class::addConstructorAndPrune(), and mlir::tblgen::Class::addMethodAndPrune().