MLIR: mlir::tblgen::MethodSignature Class Reference
mlir::tblgen::MethodSignature Class Reference
This class contains the signature of a C++ method, including the return type.
#include "mlir/TableGen/Class.h"
Public Member Functions
MethodSignature (StringRef retType, StringRef name, SmallVector< MethodParameter > &&parameters)
template<typename... Parameters>
MethodSignature (StringRef retType, StringRef name, Parameters &&...parameters)
bool makesRedundant (const MethodSignature &other) const
Determine whether a method with this signature makes a method with other signature redundant.
StringRef getName () const
Get the name of the method.
unsigned getNumParameters () const
Get the number of parameters.
void writeDeclTo (raw_ostream &os) const
Write the signature as part of a method declaration.
void writeDefTo (raw_ostream &os, StringRef namePrefix) const
Write the signature as part of a method definition.
Detailed Description
This class contains the signature of a C++ method, including the return type.
method name, and method parameters.
Definition at line 116 of file Class.h.
Constructor & Destructor Documentation
MethodSignature() [1/2]
mlir::tblgen::MethodSignature::MethodSignature (StringRef retType, StringRef name, SmallVector< MethodParameter > && parameters) inline
Definition at line 118 of file Class.h.
MethodSignature() [2/2]
template<typename... Parameters> mlir::tblgen::MethodSignature::MethodSignature (StringRef retType, StringRef name, Parameters &&... parameters) inline
Definition at line 123 of file Class.h.
Member Function Documentation
getName()
StringRef mlir::tblgen::MethodSignature::getName () const inline
Get the name of the method.
Definition at line 137 of file Class.h.
getNumParameters()
unsigned mlir::tblgen::MethodSignature::getNumParameters () const inline
Get the number of parameters.
Definition at line 140 of file Class.h.
References mlir::tblgen::MethodParameter::writeDeclTo(), and mlir::tblgen::MethodParameter::writeDefTo().
makesRedundant()
bool MethodSignature::makesRedundant (const MethodSignature & other) const
Determine whether a method with this signature makes a method with other signature redundant.
This occurs if the signatures have the same name and this signature's parameteres subsume the other's.
A method that makes another method redundant with a different return type can replace the other, the assumption being that the subsuming method provides a more resolved return type, e.g. IntegerAttr vs. Attribute.
Definition at line 76 of file Class.cpp.
writeDeclTo()
void MethodSignature::writeDeclTo (raw_ostream & os) const
Write the signature as part of a method declaration.
Definition at line 81 of file Class.cpp.
References getSpaceAfterType().
writeDefTo()
void MethodSignature::writeDefTo (raw_ostream & os, StringRef namePrefix) const
Write the signature as part of a method definition.
namePrefix is to be prepended to the method name (typically namespaces for qualifying the method definition).
Definition at line 87 of file Class.cpp.
References getSpaceAfterType().
The documentation for this class was generated from the following files:
include/mlir/TableGen/Class.h
lib/TableGen/Class.cpp