MLIR: mlir::tblgen::Class Class Reference
mlir::tblgen::Class Class Reference
A class used to emit C++ classes from Tablegen.
#include "mlir/TableGen/Class.h"
Public Member Functions
Class (StringRef name)
template<typename... Parameters>
Constructor * addConstructorAndPrune (Parameters &&...parameters)
Add a new constructor to this class and prune and constructors made redundant by it.
template<typename... Parameters>
Method * addMethod (StringRef retType, StringRef name, Method::Property properties, Parameters &&...parameters)
Add a new method to this class and prune any methods made redundant by it.
template<Method::Property Properties = Method::MP_None, typename... Parameters>
Method * addMethod (StringRef retType, StringRef name, Parameters &&...parameters)
Add a method with statically-known properties.
template<Method::Property Properties = Method::MP_None, typename... Parameters>
Method * addStaticMethod (StringRef retType, StringRef name, Parameters &&...parameters)
Add a static method.
template<Method::Property Properties = Method::MP_None, typename... Parameters>
Method * addStaticInlineMethod (StringRef retType, StringRef name, Parameters &&...parameters)
Add an inline static method.
template<Method::Property Properties = Method::MP_None, typename... Parameters>
Method * addInlineMethod (StringRef retType, StringRef name, Parameters &&...parameters)
Add an inline method.
template<Method::Property Properties = Method::MP_None, typename... Parameters>
Method * declareMethod (StringRef retType, StringRef name, Parameters &&...parameters)
Add a declaration for a method.
template<Method::Property Properties = Method::MP_None, typename... Parameters>
Method * declareStaticMethod (StringRef retType, StringRef name, Parameters &&...parameters)
Add a declaration for a static method.
void newField (StringRef type, StringRef name, StringRef defaultValue="")
Creates a new field in this class.
void writeDeclTo (raw_ostream &os) const
Writes this op's class as a declaration to the given os.
void writeDefTo (raw_ostream &os) const
Writes the method definitions in this op's class to the given os.
StringRef getClassName () const
Returns the C++ class name of the op.
Protected Member Functions
void forAllMethods (llvm::function_ref< void(const Method &)> func) const
Get a list of all the methods to emit, filtering out hidden ones.
Constructor * addConstructorAndPrune (Constructor &&newCtor)
Add a new constructor if it is not made redundant by any existing constructors and prune and existing constructors made redundant.
Method * addMethodAndPrune (Method &&newMethod)
Add a new method if it is not made redundant by any existing methods and prune and existing methods made redundant.
Protected Attributes
std::string className
The C++ class name.
std::vector< Constructor > constructors
The list of constructors.
std::vector< Method > methods
The list of class methods.
SmallVector< std::string, 4 > fields
The list of class members.
Detailed Description
A class used to emit C++ classes from Tablegen.
Contains a list of public methods and a list of private fields to be emitted.
Definition at line 279 of file Class.h.
Constructor & Destructor Documentation
Class()
Class::Class (StringRef name) explicit
Definition at line 182 of file Class.cpp.
Member Function Documentation
addConstructorAndPrune() [1/2]
template<typename... Parameters> Constructor* mlir::tblgen::Class::addConstructorAndPrune (Parameters &&... parameters) inline
Add a new constructor to this class and prune and constructors made redundant by it.
Returns null if the constructor was not added. Else, returns a pointer to the new constructor.
Definition at line 287 of file Class.h.
References mlir::tblgen::Method::MP_Constructor.
addConstructorAndPrune() [2/2]
Constructor * Class::addConstructorAndPrune (Constructor && newCtor) protected
Add a new constructor if it is not made redundant by any existing constructors and prune and existing constructors made redundant.
Definition at line 249 of file Class.cpp.
References constructors, and insertAndPrune().
addInlineMethod()
template<Method::Property Properties = Method::MP_None, typename... Parameters> Method* mlir::tblgen::Class::addInlineMethod (StringRef retType, StringRef name, Parameters &&... parameters) inline
Add an inline method.
Definition at line 333 of file Class.h.
References mlir::tblgen::Method::MP_None.
addMethod() [1/2]
template<typename... Parameters> Method* mlir::tblgen::Class::addMethod (StringRef retType, StringRef name, Method::Property properties, Parameters &&... parameters) inline
Add a new method to this class and prune any methods made redundant by it.
Returns null if the method was not added (because an existing method would make it redundant). Else, returns a pointer to the new method.
Definition at line 297 of file Class.h.
References mlir::tblgen::Method::MP_None.
addMethod() [2/2]
template<Method::Property Properties = Method::MP_None, typename... Parameters> Method* mlir::tblgen::Class::addMethod (StringRef retType, StringRef name, Parameters &&... parameters) inline
Add a method with statically-known properties.
Definition at line 306 of file Class.h.
References mlir::tblgen::Method::MP_None.
addMethodAndPrune()
Method * Class::addMethodAndPrune (Method && newMethod) protected
Add a new method if it is not made redundant by any existing methods and prune and existing methods made redundant.
Definition at line 245 of file Class.cpp.
References insertAndPrune(), and methods.
addStaticInlineMethod()
template<Method::Property Properties = Method::MP_None, typename... Parameters> Method* mlir::tblgen::Class::addStaticInlineMethod (StringRef retType, StringRef name, Parameters &&... parameters) inline
Add an inline static method.
Definition at line 324 of file Class.h.
References mlir::tblgen::Method::MP_None.
addStaticMethod()
template<Method::Property Properties = Method::MP_None, typename... Parameters> Method* mlir::tblgen::Class::addStaticMethod (StringRef retType, StringRef name, Parameters &&... parameters) inline
Add a static method.
Definition at line 315 of file Class.h.
References mlir::tblgen::Method::MP_None.
declareMethod()
template<Method::Property Properties = Method::MP_None, typename... Parameters> Method* mlir::tblgen::Class::declareMethod (StringRef retType, StringRef name, Parameters &&... parameters) inline
Add a declaration for a method.
Definition at line 342 of file Class.h.
References mlir::tblgen::Method::MP_None.
declareStaticMethod()
template<Method::Property Properties = Method::MP_None, typename... Parameters> Method* mlir::tblgen::Class::declareStaticMethod (StringRef retType, StringRef name, Parameters &&... parameters) inline
Add a declaration for a static method.
Definition at line 351 of file Class.h.
References mlir::tblgen::MethodParameter::writeDeclTo(), and mlir::tblgen::MethodParameter::writeDefTo().
forAllMethods()
void mlir::tblgen::Class::forAllMethods (llvm::function_ref< void(const Method &)> func) const inline protected
Get a list of all the methods to emit, filtering out hidden ones.
Definition at line 370 of file Class.h.
Referenced by writeDeclTo(), mlir::tblgen::OpClass::writeDeclTo(), and writeDefTo().
getClassName()
StringRef mlir::tblgen::Class::getClassName () const inline
Returns the C++ class name of the op.
Definition at line 366 of file Class.h.
newField()
void Class::newField (StringRef type, StringRef name, StringRef defaultValue = "")
Creates a new field in this class.
Definition at line 184 of file Class.cpp.
References fields.
writeDeclTo()
void Class::writeDeclTo (raw_ostream & os) const
Writes this op's class as a declaration to the given os.
Definition at line 192 of file Class.cpp.
References className, fields, forAllMethods(), mlir::tblgen::Method::isPrivate(), and mlir::tblgen::Method::writeDeclTo().
writeDefTo()
void Class::writeDefTo (raw_ostream & os) const
Writes the method definitions in this op's class to the given os.
Definition at line 223 of file Class.cpp.
References className, forAllMethods(), and mlir::tblgen::Method::writeDefTo().
Member Data Documentation
className
std::string mlir::tblgen::Class::className protected
The C++ class name.
Definition at line 383 of file Class.h.
Referenced by writeDeclTo(), mlir::tblgen::OpClass::writeDeclTo(), and writeDefTo().
constructors
std::vector<Constructor> mlir::tblgen::Class::constructors protected
The list of constructors.
Definition at line 385 of file Class.h.
Referenced by addConstructorAndPrune().
fields
SmallVector<std::string, 4> mlir::tblgen::Class::fields protected
The list of class members.
Definition at line 389 of file Class.h.
Referenced by newField(), and writeDeclTo().
methods
std::vector<Method> mlir::tblgen::Class::methods protected
The list of class methods.
Definition at line 387 of file Class.h.
Referenced by addMethodAndPrune().
The documentation for this class was generated from the following files:
include/mlir/TableGen/Class.h
lib/TableGen/Class.cpp