MLIR: mlir::OperationName Class Reference
mlir::OperationName Class Reference
#include "mlir/IR/OperationSupport.h"
Public Types
using RepresentationUnion = PointerUnion< StringAttr, const AbstractOperation * >
Public Member Functions
OperationName (AbstractOperation *op)
OperationName (StringRef name, MLIRContext *context)
Form the OperationName for an op with the specified string.
StringRef getDialectNamespace () const
Return the name of the dialect this operation is registered to.
Dialect * getDialect () const
Return the dialect this operation is registered to if the dialect is loaded in the context, or nullptr if the dialect isn't loaded.
StringRef stripDialect () const
Return the operation name with dialect name stripped, if it has one.
StringRef getStringRef () const
Return the name of this operation. This always succeeds.
StringAttr getIdentifier () const
Return the name of this operation as an identifier. This always succeeds.
const AbstractOperation * getAbstractOperation () const
If this operation has a registered operation description, return it.
void print (raw_ostream &os) const
void dump () const
void * getAsOpaquePointer () const
Static Public Member Functions
static OperationName getFromOpaquePointer (const void *pointer)
Detailed Description
Definition at line 442 of file OperationSupport.h.
Member Typedef Documentation
RepresentationUnion
using mlir::OperationName::RepresentationUnion = PointerUnion<StringAttr, const AbstractOperation *>
Definition at line 445 of file OperationSupport.h.
Constructor & Destructor Documentation
OperationName() [1/2]
mlir::OperationName::OperationName (AbstractOperation * op) inline
Definition at line 447 of file OperationSupport.h.
Referenced by getFromOpaquePointer().
OperationName() [2/2]
OperationName::OperationName (StringRef name, MLIRContext * context)
Form the OperationName for an op with the specified string.
This either is a reference to an AbstractOperation if one is known, or a uniqued Identifier if not.
Definition at line 29 of file Operation.cpp.
References mlir::AbstractOperation::lookup().
Member Function Documentation
dump()
void OperationName::dump () const
Definition at line 51 of file AsmPrinter.cpp.
References print().
getAbstractOperation()
const AbstractOperation* mlir::OperationName::getAbstractOperation () const inline
If this operation has a registered operation description, return it.
Otherwise return null.
Definition at line 472 of file OperationSupport.h.
References print().
Referenced by mlir::Operation::create(), mlir::Operation::fold(), mlir::Operation::getAbstractOperation(), mlir::OpBuilder::getBlock(), mayBeValidWithoutTerminator(), mlir::AsmParserState::Impl::PartialOpDef::PartialOpDef(), and verify().
getAsOpaquePointer()
void* mlir::OperationName::getAsOpaquePointer () const inline
Definition at line 479 of file OperationSupport.h.
Referenced by llvm::PointerLikeTypeTraits< mlir::OperationName >::getAsVoidPointer(), llvm::DenseMapInfo< mlir::OperationName >::getHashValue(), and mlir::hash_value().
getDialect()
Dialect* mlir::OperationName::getDialect () const inline
Return the dialect this operation is registered to if the dialect is loaded in the context, or nullptr if the dialect isn't loaded.
Definition at line 455 of file OperationSupport.h.
Referenced by mlir::Operation::create(), mlir::Operation::fold(), mlir::Operation::getDialect(), getDialectNamespace(), and mlir::OpInterface< AffineMapAccessInterface, detail::AffineMapAccessInterfaceInterfaceTraits >::getInterfaceFor().
getDialectNamespace()
StringRef OperationName::getDialectNamespace () const
Return the name of the dialect this operation is registered to.
Definition at line 37 of file Operation.cpp.
References getDialect(), and getStringRef().
Referenced by composeLegalityCallbacks().
getFromOpaquePointer()
OperationName OperationName::getFromOpaquePointer (const void * pointer) static
Definition at line 60 of file Operation.cpp.
References OperationName().
Referenced by llvm::DenseMapInfo< mlir::OperationName >::getEmptyKey(), llvm::PointerLikeTypeTraits< mlir::OperationName >::getFromVoidPointer(), mlir::Pattern::getRootKind(), and llvm::DenseMapInfo< mlir::OperationName >::getTombstoneKey().
getIdentifier()
StringAttr OperationName::getIdentifier () const
Return the name of this operation as an identifier. This always succeeds.
Definition at line 54 of file Operation.cpp.
Referenced by mlir::OpPassManager::getNesting(), getStringRef(), mlir::PassManager::run(), and mlir::detail::OpToOpPassAdaptor::runOnOperation().
getStringRef()
StringRef OperationName::getStringRef () const
Return the name of this operation. This always succeeds.
Definition at line 49 of file Operation.cpp.
References getIdentifier().
Referenced by mlir::Op< AffineDmaStartOp, OpTrait::MemRefsNormalizable, OpTrait::VariadicOperands, OpTrait::ZeroResult, AffineMapAccessInterface::Trait >::classof(), mlir::Operation::create(), mlir::linalg::generateLibraryCallName(), mlir::OpBuilder::getBlock(), getDialectNamespace(), getLspDiagnoticFromDiag(), inferOperationTypes(), inlineCallsInSCC(), mlirLinalgFillBuiltinNamedOpRegion(), mlir::Diagnostic::operator<<(), parseClauses(), mlir::AsmPrinter::Impl::printIntegerSet(), mlir::OpState::printOpName(), stripDialect(), mlir::OpTrait::SingleBlockImplicitTerminator< TerminatorOpType >::Impl< ConcreteType >::verifyTrait(), visitInPrettyBlockOrder(), and widenOp().
print()
void OperationName::print (raw_ostream & os) const
Definition at line 49 of file AsmPrinter.cpp.
Referenced by mlir::operator<<().
stripDialect()
StringRef OperationName::stripDialect () const
Return the operation name with dialect name stripped, if it has one.
Definition at line 44 of file Operation.cpp.
References getStringRef().
Referenced by visitInPrettyBlockOrder().
The documentation for this class was generated from the following files:
include/mlir/IR/OperationSupport.h
lib/IR/AsmPrinter.cpp
lib/IR/Operation.cpp