MLIR: mlir::tblgen::Method Class Reference
mlir::tblgen::Method Class Reference
Class for holding an op's method for C++ code emission.
#include "mlir/TableGen/Class.h"
Public Types
enum Property {
MP_None = 0x0, MP_Static = 0x1, MP_Constructor = 0x2, MP_Private = 0x4,
MP_Declaration = 0x8, MP_Inline = 0x10, MP_Constexpr = 0x20 | MP_Inline, MP_StaticDeclaration = MP_Static | MP_Declaration
}
Properties (qualifiers) of class methods.
Public Member Functions
template<typename... Args>
Method (StringRef retType, StringRef name, Property property, Args &&...args)
Method (Method &&)=default
Method & operator= (Method &&)=default
virtual ~Method ()=default
MethodBody & body ()
bool isStatic () const
Returns true if this is a static method.
bool isPrivate () const
Returns true if this is a private method.
bool isInline () const
Returns true if this is an inline method.
StringRef getName () const
Returns the name of this method.
bool makesRedundant (const Method &other) const
Returns if this method makes the other method redundant.
virtual void writeDeclTo (raw_ostream &os) const
Writes the method as a declaration to the given os.
virtual void writeDefTo (raw_ostream &os, StringRef namePrefix) const
Writes the method as a definition to the given os.
Protected Attributes
Property properties
A collection of method properties.
MethodSignature methodSignature
The signature of the method.
MethodBody methodBody
The body of the method, if it has one.
Detailed Description
Class for holding an op's method for C++ code emission.
Definition at line 178 of file Class.h.
Member Enumeration Documentation
Property
enum mlir::tblgen::Method::Property
Properties (qualifiers) of class methods.
Bitfield is used here to help querying properties.
Enumerator
MP_None
MP_Static
MP_Constructor
MP_Private
MP_Declaration
MP_Inline
MP_Constexpr
MP_StaticDeclaration
Definition at line 182 of file Class.h.
Constructor & Destructor Documentation
Method() [1/2]
template<typename... Args> mlir::tblgen::Method::Method (StringRef retType, StringRef name, Property property, Args &&... args) inline
Definition at line 194 of file Class.h.
Method() [2/2]
mlir::tblgen::Method::Method (Method &&) default
~Method()
virtual mlir::tblgen::Method::~Method () virtual default
Member Function Documentation
body()
MethodBody& mlir::tblgen::Method::body () inline
Definition at line 204 of file Class.h.
getName()
StringRef mlir::tblgen::Method::getName () const inline
Returns the name of this method.
Definition at line 216 of file Class.h.
isInline()
bool mlir::tblgen::Method::isInline () const inline
Returns true if this is an inline method.
Definition at line 213 of file Class.h.
isPrivate()
bool mlir::tblgen::Method::isPrivate () const inline
Returns true if this is a private method.
Definition at line 210 of file Class.h.
Referenced by mlir::tblgen::Class::writeDeclTo(), and mlir::tblgen::OpClass::writeDeclTo().
isStatic()
bool mlir::tblgen::Method::isStatic () const inline
Returns true if this is a static method.
Definition at line 207 of file Class.h.
makesRedundant()
bool mlir::tblgen::Method::makesRedundant (const Method & other) const inline
Returns if this method makes the other method redundant.
Definition at line 219 of file Class.h.
References methodSignature, mlir::tblgen::MethodParameter::writeDeclTo(), and mlir::tblgen::MethodParameter::writeDefTo().
operator=()
Method& mlir::tblgen::Method::operator= (Method &&) default
writeDeclTo()
void Method::writeDeclTo (raw_ostream & os) const virtual
Writes the method as a declaration to the given os.
Definition at line 129 of file Class.cpp.
Referenced by mlir::tblgen::Class::writeDeclTo(), and mlir::tblgen::OpClass::writeDeclTo().
writeDefTo()
void Method::writeDefTo (raw_ostream & os, StringRef namePrefix) const virtual
Writes the method as a definition to the given os.
namePrefix is the prefix to be prepended to the method name (typically namespaces for qualifying the method definition).
Reimplemented in mlir::tblgen::Constructor.
Definition at line 145 of file Class.cpp.
Referenced by mlir::tblgen::Class::writeDefTo().
Member Data Documentation
methodBody
MethodBody mlir::tblgen::Method::methodBody protected
The body of the method, if it has one.
Definition at line 237 of file Class.h.
methodSignature
MethodSignature mlir::tblgen::Method::methodSignature protected
The signature of the method.
Definition at line 235 of file Class.h.
Referenced by makesRedundant().
properties
Property mlir::tblgen::Method::properties protected
A collection of method properties.
Definition at line 233 of file Class.h.
The documentation for this class was generated from the following files:
include/mlir/TableGen/Class.h
lib/TableGen/Class.cpp