MLIR: mlir::tblgen::OpClass Class Reference
mlir::tblgen::OpClass Class Reference
#include "mlir/TableGen/Class.h"
Public Member Functions
OpClass (StringRef name, StringRef extraClassDeclaration="")
void addTrait (Twine trait)
Adds an op trait.
void writeDeclTo (raw_ostream &os) const
Writes this op's class as a declaration to the given os.
Public Member Functions inherited from mlir::tblgen::Class
Class (StringRef name)
template<typename... Parameters>
Constructor * addConstructorAndPrune (Parameters &&...parameters)
Add a new constructor to this class and prune and constructors made redundant by it.
template<typename... Parameters>
Method * addMethod (StringRef retType, StringRef name, Method::Property properties, Parameters &&...parameters)
Add a new method to this class and prune any methods made redundant by it.
template<Method::Property Properties = Method::MP_None, typename... Parameters>
Method * addMethod (StringRef retType, StringRef name, Parameters &&...parameters)
Add a method with statically-known properties.
template<Method::Property Properties = Method::MP_None, typename... Parameters>
Method * addStaticMethod (StringRef retType, StringRef name, Parameters &&...parameters)
Add a static method.
template<Method::Property Properties = Method::MP_None, typename... Parameters>
Method * addStaticInlineMethod (StringRef retType, StringRef name, Parameters &&...parameters)
Add an inline static method.
template<Method::Property Properties = Method::MP_None, typename... Parameters>
Method * addInlineMethod (StringRef retType, StringRef name, Parameters &&...parameters)
Add an inline method.
template<Method::Property Properties = Method::MP_None, typename... Parameters>
Method * declareMethod (StringRef retType, StringRef name, Parameters &&...parameters)
Add a declaration for a method.
template<Method::Property Properties = Method::MP_None, typename... Parameters>
Method * declareStaticMethod (StringRef retType, StringRef name, Parameters &&...parameters)
Add a declaration for a static method.
void newField (StringRef type, StringRef name, StringRef defaultValue="")
Creates a new field in this class.
void writeDeclTo (raw_ostream &os) const
Writes this op's class as a declaration to the given os.
void writeDefTo (raw_ostream &os) const
Writes the method definitions in this op's class to the given os.
StringRef getClassName () const
Returns the C++ class name of the op.
Additional Inherited Members
Protected Member Functions inherited from mlir::tblgen::Class
void forAllMethods (llvm::function_ref< void(const Method &)> func) const
Get a list of all the methods to emit, filtering out hidden ones.
Constructor * addConstructorAndPrune (Constructor &&newCtor)
Add a new constructor if it is not made redundant by any existing constructors and prune and existing constructors made redundant.
Method * addMethodAndPrune (Method &&newMethod)
Add a new method if it is not made redundant by any existing methods and prune and existing methods made redundant.
Protected Attributes inherited from mlir::tblgen::Class
std::string className
The C++ class name.
std::vector< Constructor > constructors
The list of constructors.
std::vector< Method > methods
The list of class methods.
SmallVector< std::string, 4 > fields
The list of class members.
Detailed Description
Definition at line 393 of file Class.h.
Constructor & Destructor Documentation
OpClass()
OpClass::OpClass (StringRef name, StringRef extraClassDeclaration = "") explicit
Definition at line 257 of file Class.cpp.
Member Function Documentation
addTrait()
void OpClass::addTrait (Twine trait)
Adds an op trait.
Definition at line 260 of file Class.cpp.
writeDeclTo()
void OpClass::writeDeclTo (raw_ostream & os) const
Writes this op's class as a declaration to the given os.
Redefines Class::writeDeclTo to also emit traits and extra class declarations.
Definition at line 262 of file Class.cpp.
References mlir::tblgen::Class::className, mlir::tblgen::Class::forAllMethods(), mlir::tblgen::Method::isPrivate(), and mlir::tblgen::Method::writeDeclTo().
The documentation for this class was generated from the following files:
include/mlir/TableGen/Class.h
lib/TableGen/Class.cpp