MLIR: lib/Dialect/Linalg/ComprehensiveBufferize/ComprehensiveBufferize.cpp File Reference
ComprehensiveBufferize.cpp File Reference
#include "mlir/Dialect/Linalg/ComprehensiveBufferize/ComprehensiveBufferize.h"
#include <random>
#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/Dialect/Linalg/ComprehensiveBufferize/BufferizableOpInterface.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/SCF/SCF.h"
#include "mlir/Dialect/Utils/StaticValueUtils.h"
#include "mlir/Dialect/Vector/VectorOps.h"
#include "mlir/IR/AsmState.h"
#include "mlir/IR/BlockAndValueMapping.h"
#include "mlir/IR/Operation.h"
#include "mlir/IR/TypeUtilities.h"
#include "mlir/Interfaces/InferTypeOpInterface.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Pass/PassManager.h"
#include "mlir/Transforms/BufferUtils.h"
#include "llvm/ADT/DenseSet.h"
#include "llvm/ADT/ScopeExit.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/TypeSwitch.h"
#include "llvm/Support/FormatVariadic.h"
Classes
struct mlir::linalg::comprehensive_bufferize::arith_ext::ConstantOpInterface
struct mlir::linalg::comprehensive_bufferize::scf_ext::IfOpInterface
struct mlir::linalg::comprehensive_bufferize::scf_ext::ForOpInterface
struct mlir::linalg::comprehensive_bufferize::scf_ext::YieldOpInterface
struct mlir::linalg::comprehensive_bufferize::std_ext::CallOpInterface
struct mlir::linalg::comprehensive_bufferize::std_ext::ReturnOpInterface
struct mlir::linalg::comprehensive_bufferize::tensor_ext::CastOpInterface
struct mlir::linalg::comprehensive_bufferize::tensor_ext::DimOpInterface
struct mlir::linalg::comprehensive_bufferize::tensor_ext::ExtractSliceOpInterface
struct mlir::linalg::comprehensive_bufferize::tensor_ext::ExtractOpInterface
struct mlir::linalg::comprehensive_bufferize::tensor_ext::InsertSliceOpInterface
struct mlir::linalg::comprehensive_bufferize::vector_ext::TransferReadOpInterface
struct mlir::linalg::comprehensive_bufferize::vector_ext::TransferWriteOpInterface
Namespaces
mlir
Include the generated interface declarations.
mlir::linalg
mlir::linalg::comprehensive_bufferize
mlir::linalg::comprehensive_bufferize::arith_ext
mlir::linalg::comprehensive_bufferize::scf_ext
mlir::linalg::comprehensive_bufferize::std_ext
mlir::linalg::comprehensive_bufferize::tensor_ext
mlir::linalg::comprehensive_bufferize::vector_ext
Macros
#define DEBUG_TYPE "comprehensive-module-bufferize"
#define DBGS() (llvm::dbgs() << '[' << DEBUG_TYPE << "] ")
#define LDBG(X) LLVM_DEBUG(DBGS() << X)
Functions
static std::string printOperationInfo (Operation *op, bool prefix)
Print the operation name and bufferization information.
static std::string printValueInfo (Value value, bool prefix)
Print the bufferization information for the defining op or block argument.
static bool isaTensor (Type t)
static FuncOp getCalledFunction (CallOpInterface callOp)
Return the FuncOp called by callOp.
static ReturnOp getAssumedUniqueReturnOp (FuncOp funcOp)
Return the unique ReturnOp that terminates funcOp.
static void setInPlaceOpResult (OpResult opResult, bool inPlace)
Mark whether OpResult can actually be bufferized inplace.
static void setInPlaceFuncArgument (BlockArgument bbArg, bool inPlace)
Set the attribute that triggers inplace bufferization on a FuncOp argument bbArg.
static void removeBufferizationFuncArguments (BlockArgument bbArg)
Remove the attribute that triggers inplace bufferization on a FuncOp argument bbArg.
static void printTensorOrBufferInfo (std::string prefix, Value value, AsmState &state, llvm::raw_ostream &os)
Helper method printing the bufferization information of a buffer / tensor.
static bool areEquivalentExtractSliceOps (const BufferizationAliasInfo &aliasInfo, ExtractSliceOp st, InsertSliceOp sti)
Return true if the (ExtractSliceOp, InsertSliceOp) pair match (i.e.
static bool isInplaceMemoryWrite (OpOperand &opOperand, const BufferizationAliasInfo &aliasInfo)
Return true if opOperand has been decided to bufferize in-place.
static bool aliasesNonWritableBuffer (Value value, const BufferizationAliasInfo &aliasInfo)
Return true if, under current bufferization decisions, the buffer of value is not writable.
static bool aliasesInPlaceWrite (Value value, const BufferizationAliasInfo &aliasInfo)
Return true if the buffer to which operand would bufferize is equivalent to some buffer write.
static bool hasMatchingExtractSliceOp (const BufferizationAliasInfo &aliasInfo, Value value, InsertSliceOp insertOp)
Return true if value is originating from an ExtractSliceOp that matches the given InsertSliceOp.
static bool happensBefore (Operation *a, Operation *b, const DominanceInfo &domInfo)
Return true if a happens before b, i.e., a or one of its ancestors properly dominates b and b is not inside a.
static bool hasReadAfterWriteInterference (const DenseSet< OpOperand *> &usesRead, const DenseSet< OpOperand *> &usesWrite, const DominanceInfo &domInfo, const BufferizationAliasInfo &aliasInfo)
Given sets of uses and writes, return true if there is a RaW conflict under the assumption that all given reads/writes alias the same buffer and that all given writes bufferize inplace.
bool wouldCreateReadAfterWriteInterference (OpOperand &operand, OpResult result, const DominanceInfo &domInfo, const BufferizationAliasInfo &aliasInfo, bool checkConsistencyOnly=false)
Return true if bufferizing result inplace would create a conflict.
static bool wouldCreateWriteToNonWritableBuffer (OpOperand &opOperand, OpResult opResult, const BufferizationAliasInfo &aliasInfo)
Return true if bufferizing opOperand inplace with opResult would create a write to a non-writable buffer.
static Operation * getEquivalentAlloc (Value value, const BufferizationAliasInfo &aliasInfo)
Return the op with Allocate MemoryEffect if v is equivalent to an such an op.
static BlockArgument getEquivalentEnclosingFuncBBArg (Value v, const BufferizationAliasInfo &aliasInfo)
Return the first argument of the enclosing FuncOp that is equivalent to v.
static MemRefType getContiguousMemRefType (ShapedType shapedType, MemRefLayoutAttrInterface layout={}, Attribute memorySpace={})
Return a contiguous MemRefType (i.e.
static Type getContiguousOrUnrankedMemRefType (Type type, MemRefLayoutAttrInterface layout={}, Attribute memorySpace={})
Return a contiguous MemRefType (i.e.
static MemRefType getDynamicMemRefType (RankedTensorType tensorType, unsigned addressSpace=0)
Return a MemRefType to which the tensorType can be bufferized in a composable fashion.
static FunctionType getBufferizedFunctionType (MLIRContext *ctx, TypeRange argumentTypes, TypeRange resultTypes)
Return the FunctionType with argumentTypes and resultTypes where each tensor is replaced by the corresponding buffer type.
static FunctionType getOrCreateBufferizedFunctionType (FuncOp funcOp, TypeRange argumentTypes, TypeRange resultTypes, DenseMap< FuncOp, FunctionType > &bufferizedFunctionTypes)
If an entry for funcOp is available in bufferizedFunctionTypes, return it.
static void moveInsertionPointToAllocationHoistingBarrier (OpBuilder &b)
Move the insertion point of the given builder to the beginning of a surrounding block as much as possible, while not crossing any allocation hoisting barriers.
static MemRefType getAllocationTypeAndShape (OpBuilder &b, Location loc, Value shapedValue, SmallVectorImpl< Value > &dynShape)
Compute the type of the memref to use for allocating the buffer for shapedValue.
static Value createNewAllocDeallocPairForShapedValue (OpBuilder &b, Location loc, Value shapedValue, BufferizationState &state)
Create an Allocop/DeAllocOp pair, where the AllocOp is after shapedValue.getDefiningOp (or at the top of the block in case of a bbArg) and the DeallocOp is at the end of the block.
static LogicalResult bufferize (OpBuilder &b, CallOpInterface callOp, BufferizationState &state, DenseMap< FuncOp, FunctionType > &bufferizedFunctionTypes)
In a first approximation, all the function arguments of a FuncOp are marked inplaceable.
static LogicalResult bufferize (OpBuilder &b, FuncOp funcOp, BufferizationState &state)
FuncOp always creates TensorToMemRef ops.
static LogicalResult bufferizableInPlaceAnalysisImpl (OpOperand &operand, OpResult result, BufferizationAliasInfo &aliasInfo, const DominanceInfo &domInfo)
Determine if operand can be bufferized in-place with result.
static LogicalResult bufferizableInPlaceAnalysis (OpOperand &operand, BufferizationAliasInfo &aliasInfo, const DominanceInfo &domInfo)
Determine if operand can be bufferized in-place with one of the op's results.
static LogicalResult inPlaceAnalysisFuncOpBody (FuncOp funcOp, BufferizationAliasInfo &aliasInfo, const DominanceInfo &domInfo, unsigned analysisFuzzerSeed=0)
Analyze the funcOp body to determine which OpResults are inplaceable.
static LogicalResult bufferizeFuncOpInternals (FuncOp funcOp, BufferizationState &state, DenseMap< FuncOp, FunctionType > &bufferizedFunctionTypes)
static LogicalResult bufferizeFuncOpBoundary (FuncOp funcOp, BufferizationAliasInfo &aliasInfo, DenseMap< FuncOp, FunctionType > &bufferizedFunctionTypes)
Rewrite the funcOp arguments analysis return values and terminator into buffer form (using the canonical memref layout for now), according to the inPlace-bufferizable information of the function arguments.
static LogicalResult getFuncOpsOrderedByCalls (ModuleOp moduleOp, SmallVectorImpl< FuncOp > &orderedFuncOps, DenseMap< FuncOp, DenseSet< Operation *>> &callerMap)
Store all functions of the moduleOp in orderedFuncOps, sorted by callee-caller order (i.e.
static void foreachCaller (const DenseMap< FuncOp, DenseSet< Operation *>> &callerMap, FuncOp callee, llvm::function_ref< void(Operation *)> doit)
static void layoutPostProcessing (ModuleOp moduleOp)
Postprocess the linalg.buffer_layout annotation across function boundaries.
static void checkAliasInfoConsistency (FuncOp funcOp, const DominanceInfo &domInfo, const BufferizationAliasInfo &aliasInfo)
Assert that the current bufferization decisions are consistent.
static void annotateOpsWithBufferizationMarkers (Operation *op, const BufferizationAliasInfo &aliasInfo)
Annotate the IR with the result of the analysis. For testing/debugging only.
static LogicalResult mlir::linalg::comprehensive_bufferize::scf_ext::bufferizeIfOp (scf::IfOp ifOp, OpBuilder &b, BufferizationState &state)
Bufferize the scf::IfOp.
static LogicalResult mlir::linalg::comprehensive_bufferize::scf_ext::bufferizeForOp (scf::ForOp forOp, OpBuilder &b, BufferizationState &state)
Bufferize the scf::ForOp.
static bool mlir::linalg::comprehensive_bufferize::tensor_ext::isSourceEquivalentToAMatchingInplaceExtractSliceOp (const BufferizationAliasInfo &aliasInfo, InsertSliceOp insertSliceOp)
Return true if the source of a insertSliceOp bufferizes to an equivalent ExtractSliceOp that bufferizes inplace.
void mlir::linalg::comprehensive_bufferize::registerBufferizableOpInterfaceExternalModels (DialectRegistry &registry)
Register external models implemented for the BufferizableOpInterface.
Variables
constexpr StringLiteral kInPlaceResultsAttrName = "__inplace_results_attr__"
Attribute marker to specify op results that can be bufferized inPlace.
Macro Definition Documentation
DBGS
#define DBGS () (llvm::dbgs() << '[' << DEBUG_TYPE << "] ")
Definition at line 139 of file ComprehensiveBufferize.cpp.
Referenced by bufferizeFuncOpBoundary().
DEBUG_TYPE
#define DEBUG_TYPE "comprehensive-module-bufferize"
Definition at line 132 of file ComprehensiveBufferize.cpp.
Referenced by printOperationInfo().
LDBG
#define LDBG (X) LLVM_DEBUG(DBGS() << X)
Definition at line 140 of file ComprehensiveBufferize.cpp.
Referenced by aliasesInPlaceWrite(), aliasesNonWritableBuffer(), bufferizableInPlaceAnalysisImpl(), mlir::linalg::comprehensive_bufferize::tensor_ext::ExtractSliceOpInterface::bufferize(), mlir::linalg::comprehensive_bufferize::tensor_ext::InsertSliceOpInterface::bufferize(), bufferizeFuncOpInternals(), mlir::linalg::comprehensive_bufferize::bufferizeOp(), getOrCreateBufferizedFunctionType(), hasReadAfterWriteInterference(), inPlaceAnalysisFuncOpBody(), mlir::linalg::comprehensive_bufferize::tensor_ext::isSourceEquivalentToAMatchingInplaceExtractSliceOp(), setInPlaceOpResult(), and wouldCreateWriteToNonWritableBuffer().
Function Documentation
aliasesInPlaceWrite()
static bool aliasesInPlaceWrite (Value value, const BufferizationAliasInfo & aliasInfo) static
Return true if the buffer to which operand would bufferize is equivalent to some buffer write.
Definition at line 349 of file ComprehensiveBufferize.cpp.
References mlir::Value::getUses(), isInplaceMemoryWrite(), LDBG, printOperationInfo(), and printValueInfo().
Referenced by wouldCreateWriteToNonWritableBuffer().
aliasesNonWritableBuffer()
static bool aliasesNonWritableBuffer (Value value, const BufferizationAliasInfo & aliasInfo) static
Return true if, under current bufferization decisions, the buffer of value is not writable.
Definition at line 314 of file ComprehensiveBufferize.cpp.
References mlir::Value::dyn_cast(), mlir::Value::getDefiningOp(), LDBG, and printValueInfo().
Referenced by wouldCreateWriteToNonWritableBuffer().
annotateOpsWithBufferizationMarkers()
static void annotateOpsWithBufferizationMarkers (Operation * op, const BufferizationAliasInfo & aliasInfo) static
Annotate the IR with the result of the analysis. For testing/debugging only.
Definition at line 1613 of file ComprehensiveBufferize.cpp.
References mlir::Operation::getResults(), setInPlaceFuncArgument(), setInPlaceOpResult(), and mlir::Operation::walk().
Referenced by mlir::linalg::comprehensive_bufferize::runComprehensiveBufferize().
areEquivalentExtractSliceOps()
static bool areEquivalentExtractSliceOps (const BufferizationAliasInfo & aliasInfo, ExtractSliceOp st, InsertSliceOp sti) static
Return true if the (ExtractSliceOp, InsertSliceOp) pair match (i.e.
equivalent operand / result and same offset/sizes/strides specification).
This is one particular type of relationship between ops on tensors that reduce to an equivalence on buffers. This should be generalized and exposed as interfaces on the proper types.
Definition at line 291 of file ComprehensiveBufferize.cpp.
References mlir::isEqualConstantIntOrValue(), and sameOffsetsSizesAndStrides().
Referenced by hasMatchingExtractSliceOp(), and mlir::linalg::comprehensive_bufferize::tensor_ext::isSourceEquivalentToAMatchingInplaceExtractSliceOp().
bufferizableInPlaceAnalysis()
static LogicalResult bufferizableInPlaceAnalysis (OpOperand & operand, BufferizationAliasInfo & aliasInfo, const DominanceInfo & domInfo) static
Determine if operand can be bufferized in-place with one of the op's results.
Even if an op does not read or write, it may still create an alias when bufferized in-place. An example of such ops is tensor.extract_slice.
Rationale for bufferizing %1 = tensor.extract_slice %0[...] inplace:
When bufferized out of place, an ExtractSliceOp lowers to alloc + copy. This cannot change the flow of information for either the source or the result buffers.
When bufferized inplace, an ExtractSliceOp does not by itself create any read or write from memory. Instead, it has the effect of merging the alias sets of the source and the result buffers.
An analysis is required to ensure inplace bufferization would not result in RaW dependence violations.
Definition at line 1089 of file ComprehensiveBufferize.cpp.
References bufferizableInPlaceAnalysisImpl(), mlir::detail::IROperandBase::getOwner(), and mlir::success().
Referenced by mlir::linalg::comprehensive_bufferize::inPlaceAnalysis().
bufferizableInPlaceAnalysisImpl()
static LogicalResult bufferizableInPlaceAnalysisImpl (OpOperand & operand, OpResult result, BufferizationAliasInfo & aliasInfo, const DominanceInfo & domInfo) static
Determine if operand can be bufferized in-place with result.
Definition at line 1039 of file ComprehensiveBufferize.cpp.
References mlir::linalg::comprehensive_bufferize::getAliasingOpOperand(), mlir::OpOperand::getOperandNumber(), mlir::OpResult::getResultNumber(), LDBG, printValueInfo(), mlir::success(), wouldCreateReadAfterWriteInterference(), and wouldCreateWriteToNonWritableBuffer().
Referenced by bufferizableInPlaceAnalysis().
bufferize() [1/2]
static LogicalResult bufferize (OpBuilder & b, CallOpInterface callOp, BufferizationState & state, DenseMap< FuncOp, FunctionType > & bufferizedFunctionTypes) static
In a first approximation, all the function arguments of a FuncOp are marked inplaceable.
For now, it is the responsibility of the callOp bufferization to allow FuncOp that are inplaceable to write inPlace.
Definition at line 875 of file ComprehensiveBufferize.cpp.
References mlir::OpBuilder::create(), getAssumedUniqueReturnOp(), getCalledFunction(), getEquivalentAlloc(), getEquivalentEnclosingFuncBBArg(), getOrCreateBufferizedFunctionType(), mlir::Value::getType(), mlir::Type::isa(), isaTensor(), mlir::Value::replaceAllUsesWith(), mlir::Operation::setAttrs(), mlir::OpBuilder::setInsertionPoint(), and mlir::success().
Referenced by bufferizeFuncOpInternals(), and mlir::linalg::comprehensive_bufferize::bufferizeOp().
bufferize() [2/2]
static LogicalResult bufferize (OpBuilder & b, FuncOp funcOp, BufferizationState & state) static
FuncOp always creates TensorToMemRef ops.
Definition at line 1010 of file ComprehensiveBufferize.cpp.
References mlir::OpBuilder::create(), mlir::Type::dyn_cast(), getContiguousOrUnrankedMemRefType(), getDynamicMemRefType(), mlir::OpBuilder::setInsertionPointToStart(), and mlir::success().
bufferizeFuncOpBoundary()
static LogicalResult bufferizeFuncOpBoundary (FuncOp funcOp, BufferizationAliasInfo & aliasInfo, DenseMap< FuncOp, FunctionType > & bufferizedFunctionTypes) static
Rewrite the funcOp arguments analysis return values and terminator into buffer form (using the canonical memref layout for now), according to the inPlace-bufferizable information of the function arguments.
This relies on a buffer equivalence analysis of each return operand. When a result buffer is equivalent to:
a BlockArgument of funcOp, it can be dropped from the return values and becomes inplaceable at all callers. This assumes all CallOp perform the necessary work to clone operands so as to make them inplaceable. 2. an op with an Alloc effect, this currently fails bufferization but is a candidate for hoisting and creating a new inplace operand at all caller sites.
if such a hoisting for 2. is not possible (e.g. data-dependent that prevents hoisting), this is currently unsupported and will require a refcounted buffer type.
Definition at line 1311 of file ComprehensiveBufferize.cpp.
References mlir::Block::addArgument(), DBGS, mlir::Type::dyn_cast(), mlir::Block::eraseArgument(), mlir::Block::front(), mlir::Block::getArgument(), mlir::Block::getArguments(), getAssumedUniqueReturnOp(), getEquivalentAlloc(), getEquivalentEnclosingFuncBBArg(), mlir::Block::getNumArguments(), getOrCreateBufferizedFunctionType(), mlir::Value::getType(), isaTensor(), mlir::Value::replaceAllUsesWith(), mlir::OpBuilder::setInsertionPointToStart(), and mlir::success().
Referenced by mlir::linalg::comprehensive_bufferize::runComprehensiveBufferize().
bufferizeFuncOpInternals()
static LogicalResult bufferizeFuncOpInternals (FuncOp funcOp, BufferizationState & state, DenseMap< FuncOp, FunctionType > & bufferizedFunctionTypes) static
Definition at line 1214 of file ComprehensiveBufferize.cpp.
References bufferize(), mlir::linalg::comprehensive_bufferize::bufferizeOp(), mlir::failed(), mlir::failure(), isaTensor(), LDBG, mlir::PreOrder, and mlir::success().
Referenced by mlir::linalg::comprehensive_bufferize::runComprehensiveBufferize().
checkAliasInfoConsistency()
static void checkAliasInfoConsistency (FuncOp funcOp, const DominanceInfo & domInfo, const BufferizationAliasInfo & aliasInfo) static
Assert that the current bufferization decisions are consistent.
Definition at line 1593 of file ComprehensiveBufferize.cpp.
References mlir::Operation::getOpOperands(), and wouldCreateReadAfterWriteInterference().
Referenced by mlir::linalg::comprehensive_bufferize::runComprehensiveBufferize().
createNewAllocDeallocPairForShapedValue()
static Value createNewAllocDeallocPairForShapedValue (OpBuilder & b, Location loc, Value shapedValue, BufferizationState & state) static
Create an Allocop/DeAllocOp pair, where the AllocOp is after shapedValue.getDefiningOp (or at the top of the block in case of a bbArg) and the DeallocOp is at the end of the block.
Definition at line 838 of file ComprehensiveBufferize.cpp.
References mlir::OpBuilder::create(), mlir::Type::dyn_cast(), getAllocationTypeAndShape(), mlir::Value::getType(), mlir::Type::isa(), and mlir::OpBuilder::setInsertionPoint().
Referenced by mlir::linalg::comprehensive_bufferize::tensor_ext::ExtractSliceOpInterface::bufferize(), and mlir::linalg::comprehensive_bufferize::defaultAllocationCallbacks().
foreachCaller()
static void foreachCaller (const DenseMap< FuncOp, DenseSet< Operation *>> & callerMap, FuncOp callee, llvm::function_ref< void(Operation *)> doit) static
Definition at line 1501 of file ComprehensiveBufferize.cpp.
getAllocationTypeAndShape()
static MemRefType getAllocationTypeAndShape (OpBuilder & b, Location loc, Value shapedValue, SmallVectorImpl< Value > & dynShape) static
Compute the type of the memref to use for allocating the buffer for shapedValue.
Also returns (by reference in dynShape), the value for the dynamic dimensions in the returned memref type. The function may also set the insertion point to an earlier location, where the allocation should happen ("allocation hoisting").
Definition at line 791 of file ComprehensiveBufferize.cpp.
References mlir::Type::cast(), mlir::OpBuilder::create(), mlir::Value::dyn_cast(), mlir::detail::enumerate(), getContiguousMemRefType(), mlir::Value::getDefiningOp(), mlir::OpResult::getResultNumber(), mlir::Value::getType(), mlir::Type::isa(), mlir::ShapedType::isDynamic(), moveInsertionPointToAllocationHoistingBarrier(), and mlir::succeeded().
Referenced by createNewAllocDeallocPairForShapedValue().
getAssumedUniqueReturnOp()
static ReturnOp getAssumedUniqueReturnOp (FuncOp funcOp) static
Return the unique ReturnOp that terminates funcOp.
Return nullptr if there is no such unique ReturnOp.
Definition at line 165 of file ComprehensiveBufferize.cpp.
Referenced by bufferize(), and bufferizeFuncOpBoundary().
getBufferizedFunctionType()
static FunctionType getBufferizedFunctionType (MLIRContext * ctx, TypeRange argumentTypes, TypeRange resultTypes) static
Return the FunctionType with argumentTypes and resultTypes where each tensor is replaced by the corresponding buffer type.
In order for all the callers to agree, this must bufferize to the most dynamic buffer type supported. A later pass across all CallOps in the module can decide whether to simplify the types of to version according to some cost model.
Definition at line 720 of file ComprehensiveBufferize.cpp.
References getContiguousOrUnrankedMemRefType(), getDynamicMemRefType(), and rewrite().
Referenced by getOrCreateBufferizedFunctionType().
getCalledFunction()
static FuncOp getCalledFunction (CallOpInterface callOp) static
Return the FuncOp called by callOp.
Definition at line 155 of file ComprehensiveBufferize.cpp.
References mlir::SymbolTable::lookupNearestSymbolFrom().
Referenced by bufferize().
getContiguousMemRefType()
static MemRefType getContiguousMemRefType (ShapedType shapedType, MemRefLayoutAttrInterface layout = {}, Attribute memorySpace = {}) static
Return a contiguous MemRefType (i.e.
with canonical/empty layout map) with the same shape as shapedType and specified layout and addressSpace.
Definition at line 678 of file ComprehensiveBufferize.cpp.
References mlir::ShapedType::getElementType(), and mlir::ShapedType::getShape().
Referenced by getAllocationTypeAndShape(), and getContiguousOrUnrankedMemRefType().
getContiguousOrUnrankedMemRefType()
static Type getContiguousOrUnrankedMemRefType (Type type, MemRefLayoutAttrInterface layout = {}, Attribute memorySpace = {}) static
Return a contiguous MemRefType (i.e.
with canonical/empty layout map) with the same shape as shapedType and specified layout and addressSpace or an UnrankedMemRefType otherwise.
Definition at line 689 of file ComprehensiveBufferize.cpp.
References mlir::Type::cast(), getContiguousMemRefType(), mlir::getElementTypeOrSelf(), and mlir::Type::isa().
Referenced by bufferize(), mlir::linalg::comprehensive_bufferize::tensor_ext::CastOpInterface::bufferize(), and getBufferizedFunctionType().
getDynamicMemRefType()
static MemRefType getDynamicMemRefType (RankedTensorType tensorType, unsigned addressSpace = 0) static
Return a MemRefType to which the tensorType can be bufferized in a composable fashion.
The layout must be the most dynamic possible and canonicalize away once bufferization is finished.
Definition at line 702 of file ComprehensiveBufferize.cpp.
References mlir::ShapedType::kDynamicStrideOrOffset, and mlir::makeStridedLinearLayoutMap().
Referenced by bufferize(), and getBufferizedFunctionType().
getEquivalentAlloc()
static Operation * getEquivalentAlloc (Value value, const BufferizationAliasInfo & aliasInfo) static
Return the op with Allocate MemoryEffect if v is equivalent to an such an op.
Return the op with Allocate MemoryEffect if v is equivalent to such an an op.
Return null otherwise.
Definition at line 1261 of file ComprehensiveBufferize.cpp.
Referenced by bufferize(), bufferizeFuncOpBoundary(), and wouldCreateWriteToNonWritableBuffer().
getEquivalentEnclosingFuncBBArg()
static BlockArgument getEquivalentEnclosingFuncBBArg (Value v, const BufferizationAliasInfo & aliasInfo) static
Return the first argument of the enclosing FuncOp that is equivalent to v.
Return null if no such bbArg can be found.
Definition at line 1278 of file ComprehensiveBufferize.cpp.
References mlir::Value::getParentBlock(), mlir::Operation::getParentOfType(), mlir::Block::getParentOp(), mlir::Value::getType(), and mlir::Type::isa().
Referenced by bufferize(), bufferizeFuncOpBoundary(), and wouldCreateWriteToNonWritableBuffer().
getFuncOpsOrderedByCalls()
static LogicalResult getFuncOpsOrderedByCalls (ModuleOp moduleOp, SmallVectorImpl< FuncOp > & orderedFuncOps, DenseMap< FuncOp, DenseSet< Operation *>> & callerMap) static
Store all functions of the moduleOp in orderedFuncOps, sorted by callee-caller order (i.e.
callees without callers first). Store the map of FuncOp to all its callers in callerMap. Return failure() if a cycle of calls is detected or if we are unable to retrieve the called FuncOp from any CallOpInterface.
Definition at line 1449 of file ComprehensiveBufferize.cpp.
Referenced by mlir::linalg::comprehensive_bufferize::runComprehensiveBufferize().
getOrCreateBufferizedFunctionType()
static FunctionType getOrCreateBufferizedFunctionType (FuncOp funcOp, TypeRange argumentTypes, TypeRange resultTypes, DenseMap< FuncOp, FunctionType > & bufferizedFunctionTypes) static
If an entry for funcOp is available in bufferizedFunctionTypes, return it.
Otherwise, construct a new entry based on argumentTypes and resultTypes.
Definition at line 741 of file ComprehensiveBufferize.cpp.
References getBufferizedFunctionType(), and LDBG.
Referenced by bufferize(), and bufferizeFuncOpBoundary().
happensBefore()
static bool happensBefore (Operation * a, Operation * b, const DominanceInfo & domInfo) static
Return true if a happens before b, i.e., a or one of its ancestors properly dominates b and b is not inside a.
Definition at line 388 of file ComprehensiveBufferize.cpp.
References mlir::Operation::getParentOp(), mlir::Operation::isProperAncestor(), and mlir::DominanceInfo::properlyDominates().
Referenced by hasReadAfterWriteInterference().
hasMatchingExtractSliceOp()
static bool hasMatchingExtractSliceOp (const BufferizationAliasInfo & aliasInfo, Value value, InsertSliceOp insertOp) static
Return true if value is originating from an ExtractSliceOp that matches the given InsertSliceOp.
Definition at line 373 of file ComprehensiveBufferize.cpp.
References areEquivalentExtractSliceOps(), and mlir::linalg::comprehensive_bufferize::findValueInReverseUseDefChain().
Referenced by hasReadAfterWriteInterference().
hasReadAfterWriteInterference()
static bool hasReadAfterWriteInterference (const DenseSet< OpOperand *> & usesRead, const DenseSet< OpOperand *> & usesWrite, const DominanceInfo & domInfo, const BufferizationAliasInfo & aliasInfo) static
Given sets of uses and writes, return true if there is a RaW conflict under the assumption that all given reads/writes alias the same buffer and that all given writes bufferize inplace.
A conflict is: According to SSA use-def chains, a read R is supposed to read the result of a write W1. But because of bufferization decisions, R actually reads another write W2.
Definition at line 409 of file ComprehensiveBufferize.cpp.
References mlir::Value::cast(), mlir::linalg::comprehensive_bufferize::findLastPrecedingWrite(), mlir::linalg::comprehensive_bufferize::getAliasingOpResult(), mlir::Value::getDefiningOp(), happensBefore(), hasMatchingExtractSliceOp(), mlir::scf::insideMutuallyExclusiveBranches(), LDBG, printOperationInfo(), and printValueInfo().
inPlaceAnalysisFuncOpBody()
static LogicalResult inPlaceAnalysisFuncOpBody (FuncOp funcOp, BufferizationAliasInfo & aliasInfo, const DominanceInfo & domInfo, unsigned analysisFuzzerSeed = 0) static
Analyze the funcOp body to determine which OpResults are inplaceable.
Definition at line 1126 of file ComprehensiveBufferize.cpp.
References mlir::Operation::getOperandTypes(), mlir::Operation::getResultTypes(), mlir::BoolAttr::getValue(), isaTensor(), and LDBG.
Referenced by mlir::linalg::comprehensive_bufferize::runComprehensiveBufferize().
isaTensor()
static bool isaTensor (Type t) static
Definition at line 152 of file ComprehensiveBufferize.cpp.
References mlir::Type::isa().
Referenced by mlir::linalg::comprehensive_bufferize::AllocationHoistingBarrierOnly< OpTy >::bufferize(), bufferize(), mlir::linalg::comprehensive_bufferize::arith_ext::ConstantOpInterface::bufferize(), bufferizeFuncOpBoundary(), bufferizeFuncOpInternals(), mlir::linalg::comprehensive_bufferize::bufferizeOp(), and inPlaceAnalysisFuncOpBody().
isInplaceMemoryWrite()
static bool isInplaceMemoryWrite (OpOperand & opOperand, const BufferizationAliasInfo & aliasInfo) static
Return true if opOperand has been decided to bufferize in-place.
Definition at line 303 of file ComprehensiveBufferize.cpp.
References mlir::linalg::comprehensive_bufferize::bufferizesToMemoryWrite(), and mlir::linalg::comprehensive_bufferize::getAliasingOpResult().
Referenced by aliasesInPlaceWrite().
layoutPostProcessing()
static void layoutPostProcessing (ModuleOp moduleOp) static
Postprocess the linalg.buffer_layout annotation across function boundaries.
This is a purely mechanical process that may later become part of a separate pass with its own layout assignment heuristic.
Definition at line 1513 of file ComprehensiveBufferize.cpp.
Referenced by mlir::linalg::comprehensive_bufferize::runComprehensiveBufferize().
moveInsertionPointToAllocationHoistingBarrier()
static void moveInsertionPointToAllocationHoistingBarrier (OpBuilder & b) static
Move the insertion point of the given builder to the beginning of a surrounding block as much as possible, while not crossing any allocation hoisting barriers.
Definition at line 762 of file ComprehensiveBufferize.cpp.
References mlir::Region::front(), mlir::Region::getBlocks(), mlir::OpBuilder::getInsertionBlock(), mlir::Operation::getNumRegions(), mlir::Block::getParentOp(), mlir::Operation::getParentOp(), mlir::Operation::getRegion(), and mlir::OpBuilder::setInsertionPointToStart().
Referenced by getAllocationTypeAndShape().
printOperationInfo()
static std::string printOperationInfo (Operation * op, bool prefix = true) static
Print the operation name and bufferization information.
Definition at line 245 of file ComprehensiveBufferize.cpp.
References DEBUG_TYPE, mlir::Operation::getName(), mlir::Operation::getOpOperands(), mlir::Operation::getOpResults(), mlir::Operation::getParentOfType(), and printTensorOrBufferInfo().
Referenced by aliasesInPlaceWrite(), hasReadAfterWriteInterference(), printValueInfo(), and setInPlaceOpResult().
printTensorOrBufferInfo()
static void printTensorOrBufferInfo (std::string prefix, Value value, AsmState & state, llvm::raw_ostream & os) static
Helper method printing the bufferization information of a buffer / tensor.
Definition at line 235 of file ComprehensiveBufferize.cpp.
References mlir::Value::getType(), mlir::Type::isa(), and mlir::Value::printAsOperand().
Referenced by printOperationInfo(), and printValueInfo().
printValueInfo()
static std::string printValueInfo (Value value, bool prefix = true) static
Print the bufferization information for the defining op or block argument.
Definition at line 266 of file ComprehensiveBufferize.cpp.
References mlir::Value::getDefiningOp(), mlir::Region::getParentOfType(), mlir::Value::getParentRegion(), printOperationInfo(), printTensorOrBufferInfo(), and value.
Referenced by aliasesInPlaceWrite(), aliasesNonWritableBuffer(), bufferizableInPlaceAnalysisImpl(), and hasReadAfterWriteInterference().
removeBufferizationFuncArguments()
static void removeBufferizationFuncArguments (BlockArgument bbArg) static
Remove the attribute that triggers inplace bufferization on a FuncOp argument bbArg.
Definition at line 221 of file ComprehensiveBufferize.cpp.
References mlir::BlockArgument::getArgNumber(), mlir::BlockArgument::getOwner(), and mlir::Block::getParentOp().
Referenced by mlir::linalg::comprehensive_bufferize::runComprehensiveBufferize().
setInPlaceFuncArgument()
static void setInPlaceFuncArgument (BlockArgument bbArg, bool inPlace) static
Set the attribute that triggers inplace bufferization on a FuncOp argument bbArg.
Definition at line 212 of file ComprehensiveBufferize.cpp.
References mlir::BoolAttr::get(), mlir::BlockArgument::getArgNumber(), mlir::Value::getContext(), mlir::BlockArgument::getOwner(), and mlir::Block::getParentOp().
Referenced by annotateOpsWithBufferizationMarkers().
setInPlaceOpResult()
static void setInPlaceOpResult (OpResult opResult, bool inPlace) static
Mark whether OpResult can actually be bufferized inplace.
If inPlace is true, the use-def chain analysis has guaranteed that no subsequent write would occur to the bufferized tensor value (i.e. the result can be bufferized inplace).
Definition at line 192 of file ComprehensiveBufferize.cpp.
References mlir::Attribute::dyn_cast_or_null(), mlir::Operation::getAttr(), mlir::Operation::getNumResults(), mlir::OpResult::getOwner(), mlir::OpResult::getResultNumber(), kInPlaceResultsAttrName, LDBG, printOperationInfo(), and mlir::Operation::setAttr().
Referenced by annotateOpsWithBufferizationMarkers().
wouldCreateReadAfterWriteInterference()
bool wouldCreateReadAfterWriteInterference (OpOperand & operand, OpResult result, const DominanceInfo & domInfo, const BufferizationAliasInfo & aliasInfo, bool checkConsistencyOnly = false)
Return true if bufferizing result inplace would create a conflict.
A read R and a write W of the same alias set is a conflict if inplace bufferization of W changes the value read by R to a value different from the one that would be expected by tracing back R's origin through SSA use-def chains. A conflict can only be introduced by a new alias and/or an inplace bufferization decision.
Example: %0 = tensor.extract_slice t[...][...][1, 1] {inplace?} %1 = vector.transfer_write v1, t {inplace} : vector<5xf32>, tensor<?xf32> e = tensor.extract_slice %1 %2 = vector.transfer_write v2, %0 {inplace} : vector<6xf32>, tensor<?xf32> %3 = vector.transfer_read e, cst : tensor<?xf32>, vector<7xf32>
In the above example, the two TransferWriteOps have already been decided to bufferize inplace. Bufferizing the ExtractSliceOp inplace would create a conflict because:
According to SSA use-def chains, we expect to read the result of %1.
However, adding an alias {%0, t} would mean that the second TransferWriteOp overwrites the first one. Therefore, the TransferReadOp would no longer be reading the result of %1.
If checkConsistencyOnly is true, this function checks if there is a read-after-write conflict without bufferizing operand inplace. This would indicate a problem with the current inplace bufferization decisions.
Definition at line 583 of file ComprehensiveBufferize.cpp.
References mlir::linalg::comprehensive_bufferize::getAliasingOpOperand().
Referenced by bufferizableInPlaceAnalysisImpl(), and checkAliasInfoConsistency().
wouldCreateWriteToNonWritableBuffer()
static bool wouldCreateWriteToNonWritableBuffer (OpOperand & opOperand, OpResult opResult, const BufferizationAliasInfo & aliasInfo) static
Return true if bufferizing opOperand inplace with opResult would create a write to a non-writable buffer.
Definition at line 628 of file ComprehensiveBufferize.cpp.
References aliasesInPlaceWrite(), aliasesNonWritableBuffer(), mlir::linalg::comprehensive_bufferize::bufferizesToMemoryWrite(), mlir::IROperand< DerivedT, IRValueT >::get(), mlir::linalg::comprehensive_bufferize::getAliasingOpOperand(), getEquivalentAlloc(), getEquivalentEnclosingFuncBBArg(), LDBG, and value.
Referenced by bufferizableInPlaceAnalysisImpl().
Variable Documentation
kInPlaceResultsAttrName
constexpr StringLiteral kInPlaceResultsAttrName = "__inplace_results_attr__"
Attribute marker to specify op results that can be bufferized inPlace.
Definition at line 186 of file ComprehensiveBufferize.cpp.
Referenced by setInPlaceOpResult().