MLIR: lib/IR/MLIRContext.cpp File Reference
MLIRContext.cpp File Reference
#include "mlir/IR/MLIRContext.h"
#include "AffineExprDetail.h"
#include "AffineMapDetail.h"
#include "AttributeDetail.h"
#include "IntegerSetDetail.h"
#include "TypeDetail.h"
#include "mlir/IR/AffineExpr.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/IR/Attributes.h"
#include "mlir/IR/BuiltinDialect.h"
#include "mlir/IR/Diagnostics.h"
#include "mlir/IR/Dialect.h"
#include "mlir/IR/IntegerSet.h"
#include "mlir/IR/Location.h"
#include "mlir/IR/OpImplementation.h"
#include "mlir/IR/Types.h"
#include "mlir/Support/DebugAction.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/DenseSet.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/StringSet.h"
#include "llvm/ADT/Twine.h"
#include "llvm/Support/Allocator.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/Mutex.h"
#include "llvm/Support/RWMutex.h"
#include "llvm/Support/ThreadPool.h"
#include "llvm/Support/raw_ostream.h"
#include <memory>
Classes
class mlir::MLIRContextImpl
This is the implementation of the MLIRContext class, using the pImpl idiom.
Namespaces
mlir
Include the generated interface declarations.
Macros
#define DEBUG_TYPE "mlircontext"
Functions
static bool isThreadingGloballyDisabled ()
template<typename ValueT , typename DenseInfoT , typename KeyT , typename ConstructorFn >
static ValueT safeGetOrCreate (DenseSet< ValueT, DenseInfoT > &container, KeyT &&key, llvm::sys::SmartRWMutex< true > &mutex, bool threadingIsEnabled, ConstructorFn &&constructorFn)
A utility function to safely get or create a uniqued instance within the given set container.
template<typename T >
static ArrayRef< T > copyArrayRefInto (llvm::BumpPtrAllocator &allocator, ArrayRef< T > elements)
Copy the specified array of elements into memory managed by the provided bump pointer allocator.
static IntegerType getCachedIntegerType (unsigned width, IntegerType::SignednessSemantics signedness, MLIRContext *context)
Return an existing integer type instance if one is cached within the context.
Variables
static llvm::ManagedStatic< MLIRContextOptions > clOptions
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "mlircontext"
Definition at line 41 of file MLIRContext.cpp.
Function Documentation
copyArrayRefInto()
template<typename T > static ArrayRef<T> copyArrayRefInto (llvm::BumpPtrAllocator & allocator, ArrayRef< T > elements) static
Copy the specified array of elements into memory managed by the provided bump pointer allocator.
This assumes the elements are all PODs.
Definition at line 434 of file MLIRContext.cpp.
getCachedIntegerType()
static IntegerType getCachedIntegerType (unsigned width, IntegerType::SignednessSemantics signedness, MLIRContext * context) static
Return an existing integer type instance if one is cached within the context.
Definition at line 870 of file MLIRContext.cpp.
References mlir::emitError(), mlir::MLIRContext::getImpl(), mlir::MLIRContextImpl::int128Ty, mlir::MLIRContextImpl::int16Ty, mlir::MLIRContextImpl::int1Ty, mlir::MLIRContextImpl::int32Ty, mlir::MLIRContextImpl::int64Ty, mlir::MLIRContextImpl::int8Ty, and mlir::MLIRContextImpl::noneType.
isThreadingGloballyDisabled()
static bool isThreadingGloballyDisabled () static
Definition at line 78 of file MLIRContext.cpp.
References clOptions.
Referenced by mlir::MLIRContext::disableMultithreading().
safeGetOrCreate()
template<typename ValueT , typename DenseInfoT , typename KeyT , typename ConstructorFn > static ValueT safeGetOrCreate (DenseSet< ValueT, DenseInfoT > & container, KeyT && key, llvm::sys::SmartRWMutex< true > & mutex, bool threadingIsEnabled, ConstructorFn && constructorFn) static
A utility function to safely get or create a uniqued instance within the given set container.
Definition at line 137 of file MLIRContext.cpp.
References mlir::AffineMap::getNumDims(), mlir::AffineMap::getNumSymbols(), and mlir::AffineMap::getResults().
Referenced by mlir::MLIRContext::getAffineUniquer().
Variable Documentation
clOptions
llvm::ManagedStatic<MLIRContextOptions> clOptions static
Definition at line 76 of file MLIRContext.cpp.
Referenced by isThreadingGloballyDisabled(), mlir::MLIRContext::MLIRContext(), and mlir::registerMLIRContextCLOptions().