MLIR: mlir::x86vector::avx2 Namespace Reference
mlir::x86vector::avx2 Namespace Reference
Helpers extracted from:
Classes
struct LoweringOptions
Options for controlling specialized AVX2 lowerings.
struct TransposeLoweringOptions
Structure to control the behavior of specialized AVX2 transpose lowering.
Functions
Value mm256UnpackLoPs (ImplicitLocOpBuilder &b, Value v1, Value v2)
Lower to vector.shuffle v1, v2, [0, 8, 1, 9, 4, 12, 5, 13].
Value mm256UnpackHiPs (ImplicitLocOpBuilder &b, Value v1, Value v2)
Lower to vector.shuffle v1, v2, [0, 8, 1, 9, 4, 12, 5, 13].
Value mm256ShufflePs (ImplicitLocOpBuilder &b, Value v1, Value v2, int8_t mask)
a a b b a a b b Take an 8 bit mask, 2 bit for each position of a[0, 3) and b[0, 4): 0:127 | 128:255 b01 b23 C8 D8 | b01+4 b23+4 C8+4 D8+4
Value mm256Permute2f128Ps (ImplicitLocOpBuilder &b, Value v1, Value v2, int8_t mask)
void transpose4x8xf32 (ImplicitLocOpBuilder &ib, MutableArrayRef< Value > vs)
4x8xf32-specific AVX2 transpose lowering.
void transpose8x8xf32 (ImplicitLocOpBuilder &ib, MutableArrayRef< Value > vs)
8x8xf32-specific AVX2 transpose lowering.
void populateSpecializedTransposeLoweringPatterns (RewritePatternSet &patterns, LoweringOptions options=LoweringOptions(), int benefit=10)
Insert specialized transpose lowering patterns.
Detailed Description
Helpers extracted from:
clang/lib/Headers/avxintrin.h
clang/test/CodeGen/X86/avx-builtins.c
clang/test/CodeGen/X86/avx2-builtins.c
clang/test/CodeGen/X86/avx-shuffle-builtins.c as well as the Intel Intrinsics Guide (https://www.intel.com/content/www/us/en/docs/intrinsics-guide/index.html) make it easier to just implement known good lowerings. All intrinsics correspond 1-1 to the Intel definition.
Function Documentation
mm256Permute2f128Ps()
Value mlir::x86vector::avx2::mm256Permute2f128Ps (ImplicitLocOpBuilder & b, Value v1, Value v2, int8_t mask)
Definition at line 55 of file AVXTranspose.cpp.
References mlir::ImplicitLocOpBuilder::create().
Referenced by transpose4x8xf32(), and transpose8x8xf32().
mm256ShufflePs()
Value mlir::x86vector::avx2::mm256ShufflePs (ImplicitLocOpBuilder & b, Value v1, Value v2, int8_t mask)
a a b b a a b b Take an 8 bit mask, 2 bit for each position of a[0, 3) and b[0, 4): 0:127 | 128:255 b01 b23 C8 D8 | b01+4 b23+4 C8+4 D8+4
a a b b a a b b Takes an 8 bit mask, 2 bit for each position of a[0, 3) and b[0, 4): 0:127 | 128:255 b01 b23 C8 D8 | b01+4 b23+4 C8+4 D8+4
Definition at line 40 of file AVXTranspose.cpp.
References mlir::ImplicitLocOpBuilder::create().
Referenced by transpose4x8xf32(), and transpose8x8xf32().
mm256UnpackHiPs()
Value mlir::x86vector::avx2::mm256UnpackHiPs (ImplicitLocOpBuilder & b, Value v1, Value v2)
Lower to vector.shuffle v1, v2, [0, 8, 1, 9, 4, 12, 5, 13].
Definition at line 31 of file AVXTranspose.cpp.
References mlir::ImplicitLocOpBuilder::create().
Referenced by transpose4x8xf32(), and transpose8x8xf32().
mm256UnpackLoPs()
Value mlir::x86vector::avx2::mm256UnpackLoPs (ImplicitLocOpBuilder & b, Value v1, Value v2)
Lower to vector.shuffle v1, v2, [0, 8, 1, 9, 4, 12, 5, 13].
Definition at line 25 of file AVXTranspose.cpp.
References mlir::ImplicitLocOpBuilder::create().
Referenced by transpose4x8xf32(), and transpose8x8xf32().
populateSpecializedTransposeLoweringPatterns()
void mlir::x86vector::avx2::populateSpecializedTransposeLoweringPatterns (RewritePatternSet & patterns, LoweringOptions options = LoweringOptions(), int benefit = 10)
Insert specialized transpose lowering patterns.
Definition at line 205 of file AVXTranspose.cpp.
References mlir::RewritePatternSet::add(), mlir::RewritePatternSet::getContext(), and options.
Referenced by mlir::x86vector::avx2::LoweringOptions::setTransposeOptions().
transpose4x8xf32()
void mlir::x86vector::avx2::transpose4x8xf32 (ImplicitLocOpBuilder & ib, MutableArrayRef< Value > vs)
4x8xf32-specific AVX2 transpose lowering.
AVX2 4x8xf32-specific transpose lowering using a "C intrinsics" model.
Definition at line 79 of file AVXTranspose.cpp.
References mlir::Builder::getContext(), mm256Permute2f128Ps(), mm256ShufflePs(), mm256UnpackHiPs(), and mm256UnpackLoPs().
Referenced by TransposeOpLowering::matchAndRewrite().
transpose8x8xf32()
void mlir::x86vector::avx2::transpose8x8xf32 (ImplicitLocOpBuilder & ib, MutableArrayRef< Value > vs)
8x8xf32-specific AVX2 transpose lowering.
AVX2 8x8xf32-specific transpose lowering using a "C intrinsics" model.
Definition at line 104 of file AVXTranspose.cpp.
References mlir::Builder::getContext(), mm256Permute2f128Ps(), mm256ShufflePs(), mm256UnpackHiPs(), and mm256UnpackLoPs().
Referenced by TransposeOpLowering::matchAndRewrite().