MLIR: mlir::linalg::comprehensive_bufferize::scf_ext Namespace Reference
mlir::linalg::comprehensive_bufferize::scf_ext Namespace Reference
Classes
struct ForOpInterface
struct IfOpInterface
struct YieldOpInterface
Functions
static LogicalResult bufferizeIfOp (scf::IfOp ifOp, OpBuilder &b, BufferizationState &state)
Bufferize the scf::IfOp.
static LogicalResult bufferizeForOp (scf::ForOp forOp, OpBuilder &b, BufferizationState &state)
Bufferize the scf::ForOp.
Function Documentation
bufferizeForOp()
static LogicalResult mlir::linalg::comprehensive_bufferize::scf_ext::bufferizeForOp (scf::ForOp forOp, OpBuilder & b, BufferizationState & state) static
Bufferize the scf::ForOp.
This function is called after the YieldOp was bufferized.
Definition at line 1963 of file ComprehensiveBufferize.cpp.
References mlir::linalg::comprehensive_bufferize::BufferizationState::aliasInfo, mlir::linalg::comprehensive_bufferize::BufferizationAliasInfo::areEquivalentBufferizedValues(), mlir::linalg::comprehensive_bufferize::BufferizationState::lookupBuffer(), and mlir::success().
Referenced by mlir::linalg::comprehensive_bufferize::scf_ext::YieldOpInterface::bufferize().
bufferizeIfOp()
static LogicalResult mlir::linalg::comprehensive_bufferize::scf_ext::bufferizeIfOp (scf::IfOp ifOp, OpBuilder & b, BufferizationState & state) static
Bufferize the scf::IfOp.
This function is called after the YieldOp was bufferized.
Definition at line 1857 of file ComprehensiveBufferize.cpp.
References mlir::linalg::comprehensive_bufferize::BufferizationState::aliasInfo, mlir::linalg::comprehensive_bufferize::BufferizationAliasInfo::createAliasInfoEntry(), mlir::failure(), mlir::linalg::comprehensive_bufferize::getResultBuffer(), mlir::linalg::comprehensive_bufferize::BufferizationState::mapBuffer(), mlir::OpBuilder::setInsertionPoint(), and mlir::success().
Referenced by mlir::linalg::comprehensive_bufferize::scf_ext::YieldOpInterface::bufferize().