MLIR: mlir::linalg::comprehensive_bufferize Namespace Reference
mlir::linalg::comprehensive_bufferize Namespace Reference
Namespaces
arith_ext
linalg_ext
scf_ext
std_ext
tensor_ext
vector_ext
Classes
struct AllocationCallbacks
Callback functions that are used to allocate/deallocate/copy memory buffers.
struct AllocationHoistingBarrierOnly
AllocationHoistingBarrierOnly is an external implementation of BufferizableOpInterface for ops that are (not yet) bufferizable, but are known to be allocation hoisting barriers.
class BufferizationAliasInfo
The BufferizationAliasInfo class maintains a list of buffer aliases and equivalence classes to support bufferization.
struct BufferizationOptions
struct BufferizationState
BufferizationState keeps track of bufferization state and provides access to the results of the analysis.
struct PostAnalysisStep
PostAnalysisSteps can be registered with BufferizationOptions and are executed after the analysis, but before bufferization.
Enumerations
enum BufferRelation { BufferRelation::None, BufferRelation::Equivalent }
Specify fine-grain relationship between buffers to enable more analysis.
Functions
SmallVector< OpOperand * > getAliasingOpOperand (OpResult result)
Determine which OpOperand* will alias with result if the op is bufferized in place.
OpResult getAliasingOpResult (OpOperand &opOperand)
Determine which OpResult will alias with opOperand if the op is bufferized in place.
bool bufferizesToMemoryRead (OpOperand &opOperand)
Return true if opOperand bufferizes to a memory read.
bool bufferizesToMemoryWrite (OpOperand &opOperand)
Return true if opOperand bufferizes to a memory write.
bool bufferizesToAliasOnly (OpOperand &opOperand)
Return true if opOperand does neither read nor write but bufferizes to an alias.
bool isValueRead (Value value)
Return true if the given value is read by an op that bufferizes to a memory read.
BufferRelation bufferRelation (OpOperand &opOperand)
Return the relationship between the operand and the its corresponding OpResult that it may alias with.
llvm::SetVector< Value > findValueInReverseUseDefChain (Value value, std::function< bool(Value)> condition)
Starting from value, follow the use-def chain in reverse, always selecting the aliasing OpOperands.
Value findLastPrecedingWrite (Value value)
Find the Value of the last preceding write of a given Value.
Value getResultBuffer (OpBuilder &b, OpResult result, BufferizationState &state)
Return the result buffer (memref) for a given OpResult (tensor).
LogicalResult inPlaceAnalysis (SmallVector< Operation *> &ops, BufferizationAliasInfo &aliasInfo, const DominanceInfo &domInfo, unsigned analysisFuzzerSeed=0)
Analyze the ops to determine which OpResults are inplaceable.
Optional< Value > defaultAllocationFn (OpBuilder &b, Location loc, MemRefType type, const SmallVector< Value > &dynShape)
Default allocation function that is used by the comprehensive bufferization pass.
void defaultDeallocationFn (OpBuilder &b, Location loc, Value allocatedBuffer)
Default deallocation function that is used by the comprehensive bufferization pass.
void defaultMemCpyFn (OpBuilder &b, Location loc, Value from, Value to)
Default memory copy function that is used by the comprehensive bufferization pass.
std::unique_ptr< AllocationCallbacks > defaultAllocationCallbacks ()
Return default allocation callbacks.
LogicalResult bufferizeOp (Operation *op, BufferizationState &state, DenseMap< FuncOp, FunctionType > *bufferizedFunctionTypes=nullptr)
Bufferize one particular op.
void registerBufferizableOpInterfaceExternalModels (DialectRegistry &registry)
Register external models implemented for the BufferizableOpInterface.
LogicalResult runComprehensiveBufferize (ModuleOp moduleOp, const BufferizationOptions &options)
Variables
static constexpr int64_t kBufferAlignments = 128
Enumeration Type Documentation
BufferRelation
enum mlir::linalg::comprehensive_bufferize::BufferRelation strong
Specify fine-grain relationship between buffers to enable more analysis.
Enumerator
None
Equivalent
Definition at line 31 of file BufferizableOpInterface.h.
Function Documentation
bufferizeOp()
LogicalResult mlir::linalg::comprehensive_bufferize::bufferizeOp (Operation * op, BufferizationState & state, DenseMap< FuncOp, FunctionType > * bufferizedFunctionTypes = nullptr)
Bufferize one particular op.
bufferizedFunctionTypes (resp. globalCreator) are expected to be non-null if op is a CallOpInterface (resp. GlobalCreator).
Definition at line 1184 of file ComprehensiveBufferize.cpp.
References bufferize(), mlir::Operation::emitError(), mlir::Operation::getContext(), mlir::Operation::getOperandTypes(), mlir::Operation::getResultTypes(), isaTensor(), LDBG, and mlir::success().
Referenced by bufferizeFuncOpInternals().
bufferizesToAliasOnly()
bool mlir::linalg::comprehensive_bufferize::bufferizesToAliasOnly (OpOperand & opOperand)
Return true if opOperand does neither read nor write but bufferizes to an alias.
Return false if the op is not bufferizable.
Definition at line 223 of file BufferizableOpInterface.cpp.
References mlir::detail::IROperandBase::getOwner().
Referenced by isValueRead().
bufferizesToMemoryRead()
bool mlir::linalg::comprehensive_bufferize::bufferizesToMemoryRead (OpOperand & opOperand)
Return true if opOperand bufferizes to a memory read.
Return true if the op is not bufferizable.
Definition at line 197 of file BufferizableOpInterface.cpp.
References mlir::detail::IROperandBase::getOwner().
Referenced by getResultBuffer(), and isValueRead().
bufferizesToMemoryWrite()
bool mlir::linalg::comprehensive_bufferize::bufferizesToMemoryWrite (OpOperand & opOperand)
Return true if opOperand bufferizes to a memory write.
Return true if the op is not bufferizable.
Definition at line 210 of file BufferizableOpInterface.cpp.
References mlir::detail::IROperandBase::getOwner().
Referenced by getResultBuffer(), isInplaceMemoryWrite(), and wouldCreateWriteToNonWritableBuffer().
bufferRelation()
BufferRelation mlir::linalg::comprehensive_bufferize::bufferRelation (OpOperand & opOperand)
Return the relationship between the operand and the its corresponding OpResult that it may alias with.
Return None if the op is not bufferizable.
Definition at line 258 of file BufferizableOpInterface.cpp.
References mlir::detail::IROperandBase::getOwner(), and None.
Referenced by mlir::linalg::comprehensive_bufferize::BufferizationAliasInfo::bufferizeInPlace(), and mlir::linalg::comprehensive_bufferize::linalg_ext::InitTensorEliminationStep::eliminateInitTensors().
defaultAllocationCallbacks()
std::unique_ptr< AllocationCallbacks > mlir::linalg::comprehensive_bufferize::defaultAllocationCallbacks ()
Return default allocation callbacks.
Definition at line 1728 of file ComprehensiveBufferize.cpp.
References createNewAllocDeallocPairForShapedValue(), defaultAllocationFn(), defaultDeallocationFn(), and defaultMemCpyFn().
defaultAllocationFn()
Optional< Value > mlir::linalg::comprehensive_bufferize::defaultAllocationFn (OpBuilder & b, Location loc, MemRefType type, const SmallVector< Value > & dynShape)
Default allocation function that is used by the comprehensive bufferization pass.
The default currently creates a ranked memref using memref.alloc.
Definition at line 1164 of file ComprehensiveBufferize.cpp.
References mlir::OpBuilder::create(), mlir::Builder::getI64IntegerAttr(), and kBufferAlignments.
Referenced by defaultAllocationCallbacks().
defaultDeallocationFn()
void mlir::linalg::comprehensive_bufferize::defaultDeallocationFn (OpBuilder & b, Location loc, Value allocatedBuffer)
Default deallocation function that is used by the comprehensive bufferization pass.
It expects to recieve back the value called from the defaultAllocationFn.
Definition at line 1172 of file ComprehensiveBufferize.cpp.
References mlir::OpBuilder::create().
Referenced by defaultAllocationCallbacks().
defaultMemCpyFn()
void mlir::linalg::comprehensive_bufferize::defaultMemCpyFn (OpBuilder & b, Location loc, Value from, Value to)
Default memory copy function that is used by the comprehensive bufferization pass.
Creates a linalg.copy op.
Definition at line 1177 of file ComprehensiveBufferize.cpp.
References mlir::OpBuilder::create().
Referenced by defaultAllocationCallbacks().
findLastPrecedingWrite()
Value mlir::linalg::comprehensive_bufferize::findLastPrecedingWrite (Value value)
Find the Value of the last preceding write of a given Value.
Note: Unknown ops are handled conservatively and assumed to be writes. Furthermore, BlockArguments are also assumed to be writes. There is no analysis across block boundaries.
Note: When reaching an end of the reverse SSA use-def chain, that value is returned regardless of whether it is a memory write or not.
Definition at line 300 of file BufferizableOpInterface.cpp.
References mlir::Value::cast(), findValueInReverseUseDefChain(), and mlir::Value::getDefiningOp().
Referenced by getResultBuffer(), and hasReadAfterWriteInterference().
findValueInReverseUseDefChain()
llvm::SetVector< Value > mlir::linalg::comprehensive_bufferize::findValueInReverseUseDefChain (Value value, std::function< bool(Value)> condition)
Starting from value, follow the use-def chain in reverse, always selecting the aliasing OpOperands.
Find and return Values for which condition evaluates to true. OpOperands of such matching Values are not traversed any further.
When reaching the end of a chain (BlockArgument or Value without aliasing OpOperands), also return the last Value of that chain.
Example:
                          8
                          |
6* 7* +--—+-—+ | | | | 2* 3 4* 5 | | | | +-------—+-------—+-------—+ | 1
In the above example, Values with a star satisfy the condition. When starting the traversal from Value 1, the resulting SetVector is: { 2, 7, 8, 5 }
Definition at line 273 of file BufferizableOpInterface.cpp.
References mlir::Value::cast(), getAliasingOpOperand(), and mlir::Value::isa().
Referenced by mlir::linalg::comprehensive_bufferize::linalg_ext::InitTensorEliminationStep::eliminateInitTensors(), findLastPrecedingWrite(), and hasMatchingExtractSliceOp().
getAliasingOpOperand()
SmallVector< OpOperand * > mlir::linalg::comprehensive_bufferize::getAliasingOpOperand (OpResult result)
Determine which OpOperand* will alias with result if the op is bufferized in place.
Return an empty vector if the op is not bufferizable.
Definition at line 178 of file BufferizableOpInterface.cpp.
References mlir::Value::getDefiningOp().
Referenced by bufferizableInPlaceAnalysisImpl(), mlir::linalg::comprehensive_bufferize::linalg_ext::InitTensorEliminationStep::eliminateInitTensors(), findValueInReverseUseDefChain(), getResultBuffer(), wouldCreateReadAfterWriteInterference(), and wouldCreateWriteToNonWritableBuffer().
getAliasingOpResult()
OpResult mlir::linalg::comprehensive_bufferize::getAliasingOpResult (OpOperand & opOperand)
Determine which OpResult will alias with opOperand if the op is bufferized in place.
Return an empty OpResult if the op is not bufferizable.
Definition at line 187 of file BufferizableOpInterface.cpp.
References mlir::detail::IROperandBase::getOwner().
Referenced by hasReadAfterWriteInterference(), isInplaceMemoryWrite(), and isValueRead().
getResultBuffer()
Value mlir::linalg::comprehensive_bufferize::getResultBuffer (OpBuilder & b, OpResult result, BufferizationState & state)
Return the result buffer (memref) for a given OpResult (tensor).
Allocate a new buffer and copy over data from the existing buffer if out-of-place bufferization is necessary.
Definition at line 324 of file BufferizableOpInterface.cpp.
References mlir::linalg::comprehensive_bufferize::BufferizationState::aliasInfo, mlir::linalg::comprehensive_bufferize::BufferizationState::allocationFns, bufferizesToMemoryRead(), bufferizesToMemoryWrite(), mlir::Value::cast(), mlir::linalg::comprehensive_bufferize::AllocationCallbacks::createAllocDeallocFn, mlir::Value::dyn_cast(), mlir::Operation::emitError(), findLastPrecedingWrite(), mlir::IROperand< DerivedT, IRValueT >::get(), getAliasingOpOperand(), mlir::Value::getDefiningOp(), mlir::Operation::getLoc(), mlir::OpResult::getOwner(), mlir::linalg::comprehensive_bufferize::BufferizationAliasInfo::isInPlace(), isValueRead(), mlir::linalg::comprehensive_bufferize::BufferizationState::lookupBuffer(), mlir::linalg::comprehensive_bufferize::AllocationCallbacks::memCpyFn, mlir::OpBuilder::setInsertionPoint(), mlir::OpBuilder::setInsertionPointAfter(), and mlir::OpBuilder::setInsertionPointToStart().
Referenced by mlir::linalg::comprehensive_bufferize::scf_ext::ForOpInterface::bufferize(), mlir::linalg::comprehensive_bufferize::tensor_ext::CastOpInterface::bufferize(), mlir::linalg::comprehensive_bufferize::tensor_ext::InsertSliceOpInterface::bufferize(), mlir::linalg::comprehensive_bufferize::vector_ext::TransferWriteOpInterface::bufferize(), and mlir::linalg::comprehensive_bufferize::scf_ext::bufferizeIfOp().
inPlaceAnalysis()
LogicalResult mlir::linalg::comprehensive_bufferize::inPlaceAnalysis (SmallVector< Operation *> & ops, BufferizationAliasInfo & aliasInfo, const DominanceInfo & domInfo, unsigned analysisFuzzerSeed = 0)
Analyze the ops to determine which OpResults are inplaceable.
Walk ops in reverse and bufferize ops greedily. This is a good starter heuristic. ExtractSliceOps are interleaved with other ops in traversal order.
Definition at line 1103 of file ComprehensiveBufferize.cpp.
References bufferizableInPlaceAnalysis(), mlir::failed(), mlir::failure(), and mlir::success().
Referenced by runComprehensiveBufferize().
isValueRead()
bool mlir::linalg::comprehensive_bufferize::isValueRead (Value value)
Return true if the given value is read by an op that bufferizes to a memory read.
Also takes into account ops that create an alias but do not read by themselves (e.g., ExtractSliceOp).
Definition at line 237 of file BufferizableOpInterface.cpp.
References bufferizesToAliasOnly(), bufferizesToMemoryRead(), getAliasingOpResult(), and mlir::Value::getUses().
Referenced by mlir::linalg::comprehensive_bufferize::tensor_ext::ExtractSliceOpInterface::bufferize(), mlir::linalg::comprehensive_bufferize::scf_ext::ForOpInterface::bufferizesToMemoryRead(), and getResultBuffer().
registerBufferizableOpInterfaceExternalModels()
void mlir::linalg::comprehensive_bufferize::registerBufferizableOpInterfaceExternalModels (DialectRegistry & registry)
Register external models implemented for the BufferizableOpInterface.
Definition at line 2530 of file ComprehensiveBufferize.cpp.
References mlir::DialectRegistry::addOpInterface().
Referenced by mlir::linalg::comprehensive_bufferize::linalg_ext::InsertSliceAnchoredInitTensorEliminationStep::run().
runComprehensiveBufferize()
LogicalResult mlir::linalg::comprehensive_bufferize::runComprehensiveBufferize (ModuleOp moduleOp, const BufferizationOptions & options)
Definition at line 1628 of file ComprehensiveBufferize.cpp.
References mlir::linalg::comprehensive_bufferize::BufferizationOptions::allocationFns, mlir::linalg::comprehensive_bufferize::BufferizationOptions::allowReturnMemref, mlir::linalg::comprehensive_bufferize::BufferizationOptions::analysisFuzzerSeed, annotateOpsWithBufferizationMarkers(), bufferizeFuncOpBoundary(), bufferizeFuncOpInternals(), checkAliasInfoConsistency(), mlir::Operation::erase(), mlir::failed(), mlir::failure(), getFuncOpsOrderedByCalls(), inPlaceAnalysis(), inPlaceAnalysisFuncOpBody(), layoutPostProcessing(), mlir::linalg::comprehensive_bufferize::BufferizationState::obsoleteOps, mlir::linalg::comprehensive_bufferize::BufferizationOptions::postAnalysisSteps, removeBufferizationFuncArguments(), mlir::linalg::comprehensive_bufferize::BufferizationAliasInfo::setBufferizesToWritableMemory(), mlir::success(), and mlir::linalg::comprehensive_bufferize::BufferizationOptions::testAnalysisOnly.
Referenced by allocationFnUsingAlloca().
Variable Documentation
kBufferAlignments
constexpr int64_t mlir::linalg::comprehensive_bufferize::kBufferAlignments = 128 static
Definition at line 28 of file ComprehensiveBufferize.h.
Referenced by allocationFnUsingAlloca(), and defaultAllocationFn().