MLIR: mlir::linalg::comprehensive_bufferize::scf_ext::ForOpInterface Struct Reference
mlir::linalg::comprehensive_bufferize::scf_ext::ForOpInterface Struct Reference
Public Member Functions
bool bufferizesToMemoryRead (Operation *op, OpOperand &opOperand) const
bool bufferizesToMemoryWrite (Operation *op, OpOperand &opOperand) const
SmallVector< OpOperand * > getAliasingOpOperand (Operation *op, OpResult opResult) const
OpResult getAliasingOpResult (Operation *op, OpOperand &opOperand) const
BufferRelation bufferRelation (Operation *op, OpOperand &opOperand) const
bool isWritable (Operation *op, Value value) const
LogicalResult bufferize (Operation *op, OpBuilder &b, BufferizationState &state) const
Detailed Description
Definition at line 1882 of file ComprehensiveBufferize.cpp.
Member Function Documentation
bufferize()
LogicalResult mlir::linalg::comprehensive_bufferize::scf_ext::ForOpInterface::bufferize (Operation * op, OpBuilder & b, BufferizationState & state) const inline
Definition at line 1926 of file ComprehensiveBufferize.cpp.
References mlir::linalg::comprehensive_bufferize::BufferizationState::aliasInfo, mlir::linalg::comprehensive_bufferize::BufferizationAliasInfo::createAliasInfoEntry(), mlir::failure(), mlir::linalg::comprehensive_bufferize::getResultBuffer(), mlir::linalg::comprehensive_bufferize::BufferizationAliasInfo::insertNewBufferEquivalence(), mlir::linalg::comprehensive_bufferize::BufferizationState::mapBuffer(), and mlir::success().
bufferizesToMemoryRead()
bool mlir::linalg::comprehensive_bufferize::scf_ext::ForOpInterface::bufferizesToMemoryRead (Operation * op, OpOperand & opOperand) const inline
Definition at line 1885 of file ComprehensiveBufferize.cpp.
References mlir::linalg::comprehensive_bufferize::isValueRead().
bufferizesToMemoryWrite()
bool mlir::linalg::comprehensive_bufferize::scf_ext::ForOpInterface::bufferizesToMemoryWrite (Operation * op, OpOperand & opOperand) const inline
Definition at line 1892 of file ComprehensiveBufferize.cpp.
bufferRelation()
BufferRelation mlir::linalg::comprehensive_bufferize::scf_ext::ForOpInterface::bufferRelation (Operation * op, OpOperand & opOperand) const inline
Definition at line 1912 of file ComprehensiveBufferize.cpp.
References mlir::linalg::comprehensive_bufferize::Equivalent.
getAliasingOpOperand()
SmallVector<OpOperand *> mlir::linalg::comprehensive_bufferize::scf_ext::ForOpInterface::getAliasingOpOperand (Operation * op, OpResult opResult) const inline
Definition at line 1899 of file ComprehensiveBufferize.cpp.
References mlir::OpResult::getResultNumber().
getAliasingOpResult()
OpResult mlir::linalg::comprehensive_bufferize::scf_ext::ForOpInterface::getAliasingOpResult (Operation * op, OpOperand & opOperand) const inline
Definition at line 1905 of file ComprehensiveBufferize.cpp.
References mlir::IROperand< DerivedT, IRValueT >::get(), mlir::Value::getType(), and mlir::Type::isa().
isWritable()
bool mlir::linalg::comprehensive_bufferize::scf_ext::ForOpInterface::isWritable (Operation * op, Value value) const inline
Definition at line 1916 of file ComprehensiveBufferize.cpp.
The documentation for this struct was generated from the following file:
lib/Dialect/Linalg/ComprehensiveBufferize/ComprehensiveBufferize.cpp