MLIR: lib/Dialect/Tensor/IR/TensorOps.cpp File Reference
TensorOps.cpp File Reference
#include "mlir/Dialect/Arithmetic/IR/Arithmetic.h"
#include "mlir/Dialect/StandardOps/Utils/Utils.h"
#include "mlir/Dialect/Tensor/IR/Tensor.h"
#include "mlir/Dialect/Utils/StaticValueUtils.h"
#include "mlir/IR/BlockAndValueMapping.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/Matchers.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/IR/TypeUtilities.h"
#include "llvm/ADT/STLExtras.h"
#include "mlir/Dialect/Tensor/IR/TensorOps.cpp.inc"
Classes
struct SliceReturnTypeCanonicalizer
Return the canonical type of the result of an extract_slice op.
struct SliceCanonicalizer
A canonicalizer wrapper to replace ExtractSliceOps.
Macros
#define GET_OP_CLASSES
Enumerations
enum SliceVerificationResult { Success, RankTooLarge, SizeMismatch, ElemTypeMismatch }
Functions
static TensorType joinShapes (TensorType one, TensorType two)
Compute a TensorType that has the joined shape knowledge of the two given TensorTypes.
static LogicalResult verify (DimOp op)
static LogicalResult verify (ExtractOp op)
static LogicalResult verify (InsertOp op)
static LogicalResult verify (GenerateOp op)
static int64_t GetNumElements (ShapedType type)
static LogicalResult verify (ReshapeOp op)
static SliceVerificationResult isRankReducedType (Type originalType, Type candidateReducedType, std::string *errMsg=nullptr)
Checks if original Type type can be rank reduced to reduced type.
template<typename OpTy >
static LogicalResult produceSliceErrorMsg (SliceVerificationResult result, OpTy op, Type expectedType, StringRef errMsg="")
static LogicalResult verify (ExtractSliceOp op)
Verifier for ExtractSliceOp.
static RankedTensorType getCanonicalSliceResultType (unsigned resultRank, RankedTensorType sourceType, ArrayRef< OpFoldResult > mixedOffsets, ArrayRef< OpFoldResult > mixedSizes, ArrayRef< OpFoldResult > mixedStrides)
Infer the canonical type of the result of an extract_slice op.
static LogicalResult foldIdentityOffsetSizeAndStrideOpInterface (OffsetSizeAndStrideOpInterface op, ShapedType shapedType)
static Value foldExtractAfterInsertSlice (ExtractSliceOp extractOp)
If we have an ExtractSliceOp consuming an InsertSliceOp with the same slice, we can return the InsertSliceOp's source directly.
static LogicalResult foldInsertAfterInsertSlice (InsertSliceOp insertOp)
If we have two consecutive InsertSliceOp writing to the same slice, we can mutate the second InsertSliceOp's destination to the first one's.
Macro Definition Documentation
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 1360 of file TensorOps.cpp.
Enumeration Type Documentation
SliceVerificationResult
enum SliceVerificationResult
Enumerator
Success
RankTooLarge
SizeMismatch
ElemTypeMismatch
Definition at line 800 of file TensorOps.cpp.
Function Documentation
foldExtractAfterInsertSlice()
static Value foldExtractAfterInsertSlice (ExtractSliceOp extractOp) static
If we have an ExtractSliceOp consuming an InsertSliceOp with the same slice, we can return the InsertSliceOp's source directly.
Definition at line 1053 of file TensorOps.cpp.
References foldIdentityOffsetSizeAndStrideOpInterface(), mlir::Value::getDefiningOp(), and mlir::succeeded().
foldIdentityOffsetSizeAndStrideOpInterface()
static LogicalResult foldIdentityOffsetSizeAndStrideOpInterface (OffsetSizeAndStrideOpInterface op, ShapedType shapedType) static
Definition at line 1031 of file TensorOps.cpp.
References mlir::failure(), mlir::getConstantIntValue(), mlir::ShapedType::getShape(), and mlir::success().
Referenced by foldExtractAfterInsertSlice(), and foldInsertAfterInsertSlice().
foldInsertAfterInsertSlice()
static LogicalResult foldInsertAfterInsertSlice (InsertSliceOp insertOp) static
If we have two consecutive InsertSliceOp writing to the same slice, we can mutate the second InsertSliceOp's destination to the first one's.
Example:
%0 = tensor.insert_slice %slice0 into %input[0, 0] [64, 64] [1, 1]
%1 = tensor.insert_slice %slice1 into %0[0, 0] [64, 64] [1, 1]
folds into:
%1 = tensor.insert_slice %slice1 into %input[0, 0] [64, 64] [1, 1]
Definition at line 1146 of file TensorOps.cpp.
References mlir::RewritePatternSet::add(), mlir::tensor::canFoldIntoConsumerOp(), mlir::canonicalizeSubViewPart(), mlir::OpBuilder::create(), mlir::OpBuilder::createOrFold(), mlir::failure(), foldIdentityOffsetSizeAndStrideOpInterface(), mlir::getConstantIntValue(), mlir::Value::getType(), mlir::ShapedType::isDynamic(), mlir::ShapedType::isDynamicStrideOrOffset(), mlir::matchConstantIndex(), mlir::matchPattern(), mlir::tensor::preservesStaticInformation(), mlir::RewriterBase::replaceOp(), mlir::RewriterBase::replaceOpWithNewOp(), mlir::succeeded(), and mlir::success().
getCanonicalSliceResultType()
static RankedTensorType getCanonicalSliceResultType (unsigned resultRank, RankedTensorType sourceType, ArrayRef< OpFoldResult > mixedOffsets, ArrayRef< OpFoldResult > mixedSizes, ArrayRef< OpFoldResult > mixedStrides) static
Infer the canonical type of the result of an extract_slice op.
Returns a type with rank resultRank that is either the rank of the rank-reduced type, or the non-rank-reduced type.
Definition at line 890 of file TensorOps.cpp.
References mlir::tensor::canFoldIntoConsumerOp(), mlir::Location::cast(), mlir::OpBuilder::create(), mlir::detail::enumerate(), mlir::failure(), mlir::getConstantIntValue(), mlir::matchConstantIndex(), mlir::matchPattern(), mlir::RewriterBase::replaceOpWithNewOp(), and mlir::success().
Referenced by SliceReturnTypeCanonicalizer::operator()().
GetNumElements()
static int64_t GetNumElements (ShapedType type) static
Definition at line 614 of file TensorOps.cpp.
References mlir::ShapedType::getShape().
Referenced by verify().
isRankReducedType()
static SliceVerificationResult isRankReducedType (Type originalType, Type candidateReducedType, std::string * errMsg = nullptr) static
Checks if original Type type can be rank reduced to reduced type.
This function is slight variant of is subsequence algorithm where not matching dimension must be 1.
Definition at line 811 of file TensorOps.cpp.
References mlir::Type::cast(), mlir::computeRankReductionMask(), ElemTypeMismatch, mlir::ShapedType::getElementType(), mlir::ShapedType::getShape(), mlir::Type::isa(), RankTooLarge, SizeMismatch, and Success.
Referenced by verify().
joinShapes()
static TensorType joinShapes (TensorType one, TensorType two) static
Compute a TensorType that has the joined shape knowledge of the two given TensorTypes.
The element types need to match.
Definition at line 130 of file TensorOps.cpp.
References mlir::RewritePatternSet::add(), mlir::Type::cast(), mlir::OpBuilder::create(), mlir::failure(), mlir::ShapedType::getDimSize(), mlir::ShapedType::getElementType(), mlir::ShapedType::getRank(), mlir::ShapedType::hasRank(), mlir::ShapedType::isDynamicDim(), mlir::OperationState::location, mlir::RewriterBase::replaceOpWithNewOp(), and mlir::success().
produceSliceErrorMsg()
template<typename OpTy > static LogicalResult produceSliceErrorMsg (SliceVerificationResult result, OpTy op, Type expectedType, StringRef errMsg = "") static
Definition at line 853 of file TensorOps.cpp.
References mlir::Type::cast(), ElemTypeMismatch, RankTooLarge, SizeMismatch, mlir::success(), and Success.
Referenced by verify().
verify() [1/6]
static LogicalResult verify (DimOp op) static
Definition at line 225 of file TensorOps.cpp.
References mlir::RewritePatternSet::add(), mlir::Type::cast(), mlir::Type::dyn_cast(), mlir::failure(), mlir::tensor::foldTensorCast(), mlir::Value::getDefiningOp(), mlir::Builder::getIndexAttr(), mlir::Operation::getResult(), mlir::Value::getType(), mlir::Type::isa(), mlir::RewriterBase::replaceOpWithNewOp(), mlir::succeeded(), and mlir::success().
verify() [2/6]
static LogicalResult verify (ExtractOp op) static
Definition at line 326 of file TensorOps.cpp.
References mlir::RewritePatternSet::add(), mlir::OperationState::addOperands(), mlir::OperationState::addTypes(), mlir::Attribute::dyn_cast(), mlir::failure(), mlir::DenseElementsAttr::get(), mlir::ValueRange::getType(), mlir::m_ConstantInt(), mlir::matchPattern(), mlir::RewriterBase::replaceOp(), and mlir::success().
verify() [3/6]
static LogicalResult verify (InsertOp op) static
Definition at line 430 of file TensorOps.cpp.
References mlir::Attribute::dyn_cast(), and mlir::success().
verify() [4/6]
static LogicalResult verify (GenerateOp op) static
Definition at line 452 of file TensorOps.cpp.
References mlir::RewritePatternSet::add(), mlir::Type::cast(), mlir::OpBuilder::clone(), mlir::OpBuilder::create(), mlir::OpBuilder::createBlock(), mlir::Region::end(), mlir::failure(), mlir::Block::getArguments(), mlir::Builder::getIndexType(), mlir::Block::getTerminator(), mlir::RewriterBase::inlineRegionBefore(), mlir::OperationState::location, mlir::BlockAndValueMapping::lookupOrDefault(), mlir::m_ConstantInt(), mlir::BlockAndValueMapping::map(), mlir::matchPattern(), mlir::OperationState::regions, mlir::RewriterBase::replaceOp(), mlir::RewriterBase::replaceOpWithNewOp(), mlir::success(), mlir::Block::without_terminator(), and mlir::wouldOpBeTriviallyDead().
verify() [5/6]
static LogicalResult verify (ReshapeOp op) static
Definition at line 621 of file TensorOps.cpp.
References mlir::OperationState::addAttributes(), mlir::Type::cast(), mlir::dispatchIndexOpFoldResults(), mlir::Type::dyn_cast(), mlir::ShapedType::getElementType(), mlir::Builder::getI64ArrayAttr(), GetNumElements(), mlir::getPositionsOfShapeOne(), mlir::Value::getType(), mlir::ShapedType::kDynamicSize, mlir::ShapedType::kDynamicStrideOrOffset, and mlir::success().
verify() [6/6]
static LogicalResult verify (ExtractSliceOp op) static
Verifier for ExtractSliceOp.
Definition at line 876 of file TensorOps.cpp.
References mlir::extractFromI64ArrayAttr(), isRankReducedType(), and produceSliceErrorMsg().